### ISSUE TITLE
Assembly line keeps shutting off after every recipe

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#10048]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

Refer to this for the issue
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9531

Issue was initally closed as there was a fix for it. (https://github.com/GTNewHorizons/GT5-Unofficial/pull/861)
Fix was applied to delta, no change.

Asslines connected to data banks still push data sticks to the slave connectors, and they keep updating it shutting off the assline.
![javaw_gSMDAnxqTN](https://user-images.githubusercontent.com/17811922/160288553-35fa9f8f-a6ea-4e6d-af67-0a96401c41d6.png)

@boubou19 can provide the jar that is on delta if needed
 
Please remove the datasticks update or do it properly as it's becoming really annoying instead of fixing a small issue.
Every craft that should be done in a few ticks literally takes 80+ ticks to reset, when in those 80 ticks I should have made like 20 items

### The Reality

+

### Your Proposal

Fix data stick updates or disable it until properly done.
This was pretty much done to remove old data sticks from officials, and in case some other sticks get updated, but it's clearly causing more trouble than expected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
categorizing this as a major bug, because it's creating a 225MB gregtech.log file just to log useless data. Hopefully we don't have on rolling logs so it doesn't fill up the disk, but still.

**Comment by Glease** [comment]
It'll probably go away once you take out every stick and reinsert it. Anyway, I'll add update on load.

**Comment by Sphyix** [comment]
> It'll probably go away once you take out every stick and reinsert it. Anyway, I'll add update on load.

I'll try and update soon

**Comment by Sphyix** [comment]
Sticks keep getting updated inside the data access hatch.
It updates them every few seconds
![javaw_N705R71iO5](https://user-images.githubusercontent.com/17811922/160291887-7ac3fe33-e48c-41ea-8dd5-7dde9e13addb.png)

**Comment by Glease** [comment]
So it's one of those tectech sticks... Does it happen to vanilla GT sticks, i.e. those produced by a scanner?

**Comment by Glease** [comment]
If that is the case, delta is probably missing [this patch](https://github.com/GTNewHorizons/TecTech/pull/28/files)

**Comment by Sphyix** [comment]
> So it's one of those tectech sticks... Does it happen to vanilla GT sticks, i.e. those produced by a scanner?

Yes
![javaw_yLWK05NRhh](https://user-images.githubusercontent.com/17811922/160292051-247742e2-381b-49ea-b27c-55b6d399c04c.png)

**Comment by Sphyix** [comment]
> If that is the case, delta is probably missing [this patch](https://github.com/GTNewHorizons/TecTech/pull/28/files)

@boubou19 pls update again D:

**Comment by Glease** [comment]
I might have worded it incorrectly. If it doesn't update, then it's delta missing tectech patch. If it does update, then I'm not sure what's happening here.

**Comment by Sphyix** [comment]
Not sure if delta has that, don't think so since it's way later than the 2.1.2.0 release.
Not all the sticks are updating, even the tectech ones, only some of them are updating

**Comment by Glease** [comment]
Probably need [this one](https://github.com/GTNewHorizons/GTplusplus/pull/160) as well, for GT++ stuff.

**Comment by Glease** [comment]
### Summary

TecTech research station recipe adder and GT++ assline recipe adder bypass the GT recipe adder for assline. Therefore assline recipes from those addons will not have the required metadata added, thus keep updating forever. I guess we should add a check to GT5 that crash the server if there is any invalid recipes in the recipe list...

**Comment by Connor-Colenso** [comment]
Was this ever fixed?

**Comment by Sphyix** [comment]
> Was this ever fixed?

Not sure, not easy to test as I haven't really understood how to reproduce it consistently.
I hope it is fixed

**Comment by minecraft7771** [comment]
> Was this ever fixed?

No as of 3QF this still happens for crafts that are fast (~ <3s I think)

**Comment by Glease** [comment]
I don't see anyone complaining on zeta, so probably fixed.

**Comment by POPlol333** [comment]
Because you actually have to make the recipe fast enough, and I don't know if there anyone near that on zeta, even with UHV-tiered assline it doesn't happen on LuV motor, but it does with UIV (on delta), you can try ask GDCloud if he still witness this bug

**Comment by Sphyix** [comment]
How to reproduce on 29-dev:
Setup a normal assembly line.
![javaw_mFwgWCct1w](https://user-images.githubusercontent.com/17811922/188306174-eacc107a-4731-4ef2-bdc5-be5934e5f53b.png)
Data access hatch contains zpm electric pump and motor data sticks.
I first tried electric pump, assline was behaving correctly.
I then switched to electric motors, assline stops after every recipe is completed.

Power for the assline is double UMV energy hatch
I'll upload the world and link it here soon, I guess it can make debugging easier.

**Comment by Sphyix** [comment]
Download for the world
https://drive.google.com/file/d/1fltaF5RT5WbTfNb0bqw-1XmPbPY6kGcd/view?usp=sharing

Coords of the assline:
x -91 z 9

Things to notice:
Sticks are not updating constantly anymore, so it is not connected to the issue.

**Comment by Sphyix** [comment]
Removed the world since the test I did was stopping for other reasons.
I'll test other recipes and see if I can reproduce it.
If I can't, I'll close the ticket.
Sorry

**Comment by Sphyix** [comment]
Tested various recipes, can't reproduce on the recipes that normally get stuck on delta.
I'll close this for now

**Comment by GTNHAfx237v7** [comment]
I noticed this happening to me in 2.2.0.0. though I keep my datasticks in an advanced data hatch in the assline itself.

**Comment by boubou19** [comment]
if you use alexdoru's automation, then the cause is known: the interface receiving the items has a bandwith of 9 itemstacks/s. So if you are too fast to make the recipe (ie one ticking it) then you'll end up in a situation where the assline has to wait for items, so you are good to wait for the next recipe check. 

One way to fix this is to use multiples interfaces, but then one has to figure out the rules of item inputs(it scrambles the order but not totally random) and check if they are reboot persistent. 

Anyways, the assline works correctly so no need to reopen this ticket.
