### ISSUE TITLE
Ammonium Tetrafluoroberyllate Production broken by useless dust

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#11345]
### Your GTNH Discord Username

Lord_Anarack#2705

### Your Pack Version

RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Ammonium Tetrafluoroberyllate can be produced

### The Reality

Useless Beryllium Hydroxide Dust is produced instead breaking the LFTR fuel chain.

### Your Proposal

Remove the useless dust or add a circuit to fix the recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
This is still in play in 2.2.0.0. The beryllium hydroxide dust needs to be removed, or a circuit added to its dehydrator recipe.

**Comment by Anarack** [comment]
Fixed, LFTR fuel chain fully working

**Comment by perfectlogic3** [comment]
![image](https://user-images.githubusercontent.com/51654196/200171924-8058cffc-7e08-4c5c-93fe-9da952895749.png)
It is still buggy, the recipes are still conflicting with each other.
