### ISSUE TITLE
Light Level/Chunk Border graphical view is bugged

### ISSUE THREAD

**Issue by Ixumi** [GTNewHorizons/GT-New-Horizons-Modpack#12680]
### Your GTNH Discord Username

Synz#3336

### Your Pack Version

2.2.0.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Press F7 to view light level or F9 to view light levels or chunk borders. Expect to have straight lines which identify the borders and light levels

### The Reality

F7 and F9 View is bugged with sketchy lines and when moving, they move as well.
![Screenshot_1](https://user-images.githubusercontent.com/43588215/220532287-dd8cf7f8-7906-420a-b097-ca2cde57062a.png)

### Your Proposal

Have straight lines without a graphical bug while moving with the F7/F9 view open.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ixumi** [comment]
I have tried a fresh install of 2.2.0.0 as well with and without Optifine and nothing seems to change it. It also only happens server sided, but it works fine in singleplayer.

**Comment by Ixumi** [comment]
Solution has been found. Apparently if you go to far from spawn (Coordinates 0, 0), it bugs out the F7/F9 View and makes it look like the screenshot above.

**Comment by boubou19** [comment]
this bug is annoying and should be fixed

**Comment by Ethryan** [comment]
I heard about this bug somewhere, I think it’s caused by a rounding error somewhere in vanilla minecraft code. It wasn’t fixed properly until recently from what I know.

**Comment by Ixumi** [comment]
As far as I know, I've only seen it happen past 1000000 blocks, It might even be lower, but some further testing can be done with it to find out the exact integer limit for when it breaks or so.

**Comment by Glease** [comment]
I'd assume floating point rounding error. I'd be glad if someone can figure out how vanilla is doing it. It happens to structurelib hologram as well.

**Comment by eigenraven** [comment]
Usually this happens if you render something at large coordinates and expect the transformation matrix to shift it back near 0 in the device space for rendering, instead int coordinates need to be pre-transformed relative to the camera position before making them into floats passed to opengl

**Comment by Ethryan** [comment]
Found something that references this error i think, [Link](https://minecraft.fandom.com/wiki/Java_Edition_distance_effects)
