### ISSUE TITLE
System freeze with exit game confirmation

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14575]
### Your GTNH Discord Username

lily_blanc

### Your Pack Version

latest nightly

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

pressed the x on the window to close game, confirmation window would appear every tick being unactionable due to overlap, had to forcibly end the process
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38961580/7cd307ba-0b81-4d9a-831f-711561cd5f64)

### Crash Report

is slowly bringing my system down as we speak, if left toit's own devices can probably be barely stopped due to how much of a system impact it makes...

update, it hard froze my system had to switch using CTRL ALT FN to kill the process and recover

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12708471/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Rika-TH** [comment]
log doesn't seem relevant, nor do any other log I'm seeing atleast

**Comment by Alexdoru** [comment]
@eigenraven does the method `Display.isCloseRequested()` behaves differently with lwjgl3ify ? When I tested it on java 8 it would return true only one when you click the close button and apparently in this tickets it justs returns true constantly

**Comment by eigenraven** [comment]
It's possible I forgot to reset the internal flag once you call isCloseRequested...

**Comment by mitchej123** [comment]
@Alexdoru Might be a good idea to check if LWJGL3ify is present, and disable unless the version includes raven's fix....

**Comment by Alexdoru** [comment]
@Rika-TH try with fixed version of https://github.com/GTNewHorizons/lwjgl3ify/releases/tag/1.5.1 it should work now

**Comment by Rika-TH** [comment]
@Alexdoru assuming it should just be an extract and replace then it's kinda better? 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38961580/bc176d51-3487-4625-98f1-8dd735e2a8ff)
cannot get my screenshot selection to work AT ALL though this time, it's constantly running and displaying even in the softwares frozen overlay

**Comment by Rika-TH** [comment]
but still not fixed, just doesn't display a black hole really is the only improvement

**Comment by Alexdoru** [comment]
well idk, @eigenraven ?

**Comment by Rika-TH** [comment]
just loaded the nightly from 10hrs ago (09/25) and it would seem to now be working as expected, loading up the previous nightly (09/24) still has the issue, I'd have to assume it was just improper use of the fix

this is all done with openJDK20 on Plasma if any more detailed info is needed assuming this isn't just that the fix you sent was improperly applied by me then feel free to ask otherwise close the issue I s'pose
