### ISSUE TITLE
Apply the filter of an ME Storage Bus also to extracting items from the connected inventory.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14733]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.4.1

### Your Proposal

I actually don't know if this behavior is intended or not, if this is actually a bug then elevate this issue to a bug report.

Setup:
Place a chest and put stone and dirt blocks into it.
Attach a ME Storage Bus to the chest.
Set the filter in the storage bus to whitelist stone.

In this setup, the ME network can only insert stone into the chest, as the filter specifies. However, dirt can still be extracted from the chest, both manually through a terminal and by automation with an export bus or stocking bus.

I suggest changing this behavior so that the filter of the storage bus is respected for both insertion and extraction.

### Your Goal

I ran into the issue when trying to interface between two ME networks in a more complex setup, using the interface/storage bus combo to expose items from a network A to another network B. However I did not want to expose all the items, only those specified by a filter. However, network B could still withdraw any item from network A, regardless of the filter setting. At first I thought this was an issue with the interface/storage bus connection; however the same behavior occurs when the storage bus is simply placed on a chest.

### Your Vision

Advanced ME networking and automation.

More intuitive behavior of the filter of a storage bus.

Bug fix (if this behavior is not intended).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by ivelieu** [comment]
I agree this should be fixed. Storage busses are only useful for filtering insertion currently and it'd be nice to have.
Although I will say you can virtually always replicate whatever filtered extraction behavior you want, by instead using an import bus and a filtered insertion on the other endpoint where you wanted the item to be extracted to. Import busses are just as fast as export busses, however stocking mode interfaces are much faster and it is currently impossible to achieve interface stocking speed without IO ports due to this no filtered export option. 


Here is demo screenshot of what AbdielKavash is describing the issue to be, where dirt should not be stocked by the interface:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/28797826/07e9f5ba-e28b-4370-b7e7-14a3f8215ab7)

However, again: it is possible to do much faster than the interface stocking on filtered export by using IO ports with partitioned cells, which you can do on a filtered extract basis. I can give a demo setup of that if you want @AbdielKavash.

**Comment by AbdielKavash** [comment]
Right, I know that there are other ways to do this (and I have already fixed my existing setup). Still, I think it would be nice if this could be fixed/changed.

**Comment by jude123412** [comment]
This still exists and the work around is to filter item/fluids inside tanks/chest which is quite annoying. I'm really hoping this will be fixed.
