### ISSUE TITLE
Stocking input hatch turn off machine due to crash

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#15172]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.5.0

### Your Server

personal server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

working as stocking bus

### The Reality

its turn of machine sometimes

### Your Proposal

same intonation that may help?
99.9% sure that happen only in pull mode.

i have setup on compact that not fail:
fluid come in subnet with two 1 type fluid cell, every recipe is one single step craft. if i reduce pattern size to force many steps its start failing.

<img width="499" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/e6380d67-37fb-44f3-9715-754e09b3012a">
<img width="779" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/e7aed502-3dfb-4bbf-947a-541b3fe2c7f9">

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you post full fml-latest.log or the entire stracktrace

**Comment by lordIcocain** [comment]
<img width="502" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/1692beb7-ea0d-49f7-9518-a1ad058b30f6">

**Comment by lordIcocain** [comment]
looks like happen only in pull mode

**Comment by bombcar** [comment]
potentially unrelated but worth noting:

```
[10:06:16] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.util.ConcurrentModificationException
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:29)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:32)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:376)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:31)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:149)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:139)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75821_a(AnvilChunkLoader.java:265)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:251)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:30)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:23)
[10:06:18] [File IO Thread/INFO] [STDERR/serverutilities]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[10:06:26] [Server thread/DEBUG] [FML/]: The world 2632d4ec (World) may have leaked: seen 745 times.
```

**Comment by bombcar** [comment]
```
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot invoke "appeng.api.storage.data.IAEFluidStack.setStackSize(long)" because "request" is null
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.common.tileentities.machines.GT_MetaTileEntity_Hatch_Input_ME.endRecipeProcessing(GT_MetaTileEntity_Hatch_Input_ME.java:242)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.endRecipeProcessing(GT_MetaTileEntity_MultiBlockBase.java:1421)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:500)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at goodgenerator.blocks.tileEntity.base.LargeFusionComputer.onPostTick(LargeFusionComputer.java:318)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:547)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[07:47:41] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

This is the error

**Comment by lordIcocain** [comment]
All working fine until *something happen* after that will machine in the error, but can do recipe if i spam power button. If i replace stocking hatch it start working fine for a while then again *something happen*. 

So error in save/load NBT code?

**Comment by lordIcocain** [comment]
I think its happen because sometimes slot updating happen before end recipe check, storedFluids[i] already null and cant be checked, that explain why happen only in auto pull mode, also explain why you can get wrong positive check for "failed extract from storage" error. Also idk why, but sometimes its just cant happen on current game load, i need restart game and then it start happen. I think need rewite getStoredFluids() in stocking hatch to like a in stocking bus.

**Comment by RitumsC** [comment]
Is this issue fixed?

I believe it is crucial for 2.6.0 and (if not fixed) should be part of  #15690 .

**Comment by HoleFish** [comment]
No. I guess

**Comment by oier-namespace-std** [comment]
Advanced Stocking Input Bus also is affected by this bug ig. My Large Essentia Smeltery was often turned off due to similar crash until I turned back to normal ibus. 😞

**Comment by lordIcocain** [comment]
yeah, not fixed, just tested on last nightly

**Comment by Glease** [comment]
ME hatches/busses tend to break in awkward ways if their content is queried more than once per start/endRecipeProcessing() batch. e.g. AdvAssline used to dupe items because it'd query items more than once per batch. I ended up adding a cache as a bandaid fix, as I did not quite understand how ME hatch/bus work.

I wonder if this is somehow related.

**Comment by cytrus224** [comment]
Having similar issue on 2.6 beta. I input crafiting items into a subnet which distributes them via stocking hatches and buses to multiple AALs. My pico circuit, optical assembly and gallifreyan parts AALs started to crap itself. Did not happen when only using 1 AAL per recipe. 
![obraz](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17723060/ddb9d44c-cfe9-449c-9c87-069b4b6cff1b)

**Comment by boubou19** [comment]
should be fixed or at least mitigated in dev

**Comment by lordIcocain** [comment]
not fixed, just tested newest gt version on special test world and still getting error

**Comment by Glease** [comment]
Can you share your "special test world" in some form? we devs still have trouble replicating your issue

**Comment by lordIcocain** [comment]
https://drive.google.com/file/d/1b2OjusnAHqdvmvRpPhZ7OboooeYLrXaR/view?usp=sharing
Personal World 180, X: 54, Z: 23, Y: 133
Put in saves and then load mc. On coordinates quadruple wall shared Large Processing Factory, need just turn on them and wait, should broke pretty quick.

**Comment by Glease** [comment]
For reference 
![img](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/4586901/e1797099-29b0-48f2-9d35-d0f77f65f6cd)

**Comment by lordIcocain** [comment]
Forgot to say, but you need copy world from archive for every test. Looks like bug happen when many fluids switching, also maybe some fluids affect to it. Because i had it working for hours with many different fluids, but sometime it cant work even for minute.

**Comment by Glease** [comment]
Thanks. That's quite helpful indeed. I think I've found a new way how this could break. It looks like the internal state is not mutated in a consistent way, leading to inconsistencies in two crucial fields. Fixing this should finally allow us to get over this hideous bug.

**Comment by norbby42** [comment]
Bad news - reproduced this again :(

I tested this in my world (2.6.0-beta3, updated GregTech to 5.09.45.153 and ggfab to 0.3.19).  If I read GitHub correctly, those versions should have the fixes.

**My testcase setup:**

3 Industrial Electrolyzers:
- A: Standalone, with a Stocking ME Input Hatch and an Output Hatch (ME)
- B: Wallshared with C.  They share a Stocking ME Input Hatch and an Output Hatch (ME)
- C: Wallshared with B

Both Stocking Input Hatch (ME) are set to stock: Filled Praseodymium Extracting Nano Resin, and Filled Samarium Extracting Nano Resin.

A Digester and MCRs are producing the nano resin.  The nano resin is stored in fluid cells in AE2, and is recycled through the process.  As such, there are relatively small quantities and the Electrolyzers are able to fully process all fluids, leaving none in the system.

**Result:**
The Electrolyzers crashed seemingly at random - all 3 of them crashed at least once in my ~10 min test.  I even saw several cases where B or C crashed but the pair (using the same hatch) kept running just fine.  Possible observation: I don't think I ever had all 3 crashed at the same time.  It seemed like when there was only 1 running it tended to be fine (but it also couldn't keep up with production so never ran out of fluids to process).

It took a very long time, but I eventually had 2 MCRs crash - The MCRs do not wallshare and each have their own Stocking Input Hatch (ME).  Each of these hatches is set to stock a single fluid.

**Additional tests:**
I thought that maybe there was something on my main net that could be interfering, so I moved the whole setup to a subnet that has no read access to the mainnet (it is connected to the mainnet with an Insert Only Fluid Storage Bus on a Dual Interface so that it can push fluids out).  Storage was 2x 64k ME Multi-Fluid Storage Cells.

Same behavior persisted - Electrolyzers continued to crash.


I removed the Dual Interface connecting the subnet to the mainnet, thus completely isolating the AE2 network.  Same behavior - Electrolyzers continued to crash.


**Final Notes:**

Crashing seems to happen much more frequently when stocking multiple fluids and they are fluids that can fully empty out of the AE2 system.  Reducing the stocking size to 1 makes the setups run for much longer before crashing.

**Comment by HoleFish** [comment]
If it did "turned off due to crash" please post the log

**Comment by norbby42** [comment]
> If it did "turned off due to crash" please post the log

Sorry, to clarify it wasn't saying that it crashed, but that it failed to extract from the stocking hatch.  The server log had no stacktrace or unusual output (just reporting the online players over and over).
