### ISSUE TITLE
Certain Extra Utilities tools are functionally uncraftable

### ISSUE THREAD

**Issue by SpaceMinere** [GTNewHorizons/GT-New-Horizons-Modpack#16033]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

The Etheric Sword, Kikou, Erosion Shovel, Destruction Pickaxe, Healing Axe, and Reversing Hoe should be craftable with any oredict obsidian rod.

### The Reality

Oredict obsidian rods are not accepted in these recipes, only the one from Random Things. This rod has a recipe, but is not craftable because the GT rod and Tinkers' rod will cycle between eachother instead. Strangely, the two builders wands from exuitls accept oredicted rods.

### Your Proposal

Change the recipes for the above items so they accept oredicted obsidian rods instead of the specific rod from Random Things.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you can convert the obsidian rods to the other types

**Comment by SpaceMinere** [comment]
You can convert the GT obsidian rod to the TC tool rod and vice versa. You cannot obtain the Random Things version because there is a recipe conflict. GT -> RT and GT -> TC are identical shapeless recipes, and the GT -> TC is prioritized. Same thing goes for TC -> GT. The recipes for GT -> RT and TC -> RT exist but will never occur as they are overshadowed.

**Comment by chochem** [comment]
the conflict has been fixed since https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/626

you say you are on 2.5.1 but maybe its 2.3.1?

**Comment by SpaceMinere** [comment]
I'm definitely on 2.5.1. Maybe I still have an old file and need to reinstall the pack. I'm going to do that then test it again. Could that commit have been reversed somehow?

**Comment by chochem** [comment]
probably a bad install then yea. like a non-empty script folder

**Comment by SpaceMinere** [comment]
Ok, I had to delete the scripts folder. Recipes are correct now.
