### ISSUE TITLE
miner's backpack and food item maybe more foods

### ISSUE THREAD

**Issue by AsheX1** [GTNewHorizons/GT-New-Horizons-Modpack#16846]
### Your Pack Version

2.6.1 last release 

### Your Server

this is on a private sever we run are self (friends only)

### Java Version

Java 8

### Type of Server

None

### Your Expectation

you can not put food in the miners backpack 
BUT for some reason i can shift click a cheese sandwich into the miners backpack
clicking it to drop it in does not work but shift click does work

### The Reality

/

### Your Proposal

its not game breaking but its weird 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
good chance its fixed by https://github.com/GTNewHorizons/ForestryMC/pull/74

**Comment by AsheX1** [comment]
> good chance its fixed by [GTNewHorizons/ForestryMC#74](https://github.com/GTNewHorizons/ForestryMC/pull/74)

idk yet but also veggie sandwich can also be shift clicked in maybe all sandwich's can be shift clicked in to the miners backpack anyways still not game breaking

**Comment by GirixK** [comment]
Seems to be fixed, likely by https://github.com/GTNewHorizons/ForestryMC/pull/74 as chochem mentioned
