### ISSUE TITLE
[nightly] Frame boxes doesn't render when placed until relogin

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#17219]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.7.0.-nightly-618

### Your Server

Local forge test server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Frameboxes should renders fine.

Install and run server and client from 2.7.0.-nightly-618 https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/runs/10628911864

Try to place framebox, see invalid entity.

### The Reality

When placed frameboxes get odd metadata and doesn't render properly.

https://github.com/user-attachments/assets/dd250cb6-8d9f-4798-afca-308edd391611

### Your Proposal

Fix frameboxes metadata recieving

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SKProCH** [comment]
Seems like new frameboxes after rework heavily relies on neid extended block metadata, so removing neid from pack will cause this even in singleplayer. Probably neid should be listed as hard dep in gt5u?

Since my main server is ultramine it is doesn't support the neid due to offheap chunk storage with unsafe to manage ExtendedBlockStorage, i've want to fix that to keep using ultramine.

After a couple failed attempts to change neid mixins to support ultramine (failed), migrate mixins patches into ultramine directly (seems like fail), i removed offheap chunk storage implementation and managed to make neid works on ultramine, but got bug when i placing frames it becomes invalid blocks.
Dig out for ultramine changes that can lead to it, and found nothing - everything should works perfectly (mixins should fail if it can't be applied at least).
After that tried vanilla forge server distribution what shipped in nightly, and seems like bug also reproduceable there, so probably it should be reproduceable on zeta currently.

Also, seems like the S23PacketBlockChange packet is responsible for block updates from server. At least it responsible for block changes, soo, probably it is the problem.

Also, pinging @NotAPenguin0 as the author of new frameboxes.

I'll double-check everything tomorrow, download the client and server again to eliminate the possibility that I changed something and everything broke due to my fault.

**Comment by SKProCH** [comment]
Actually this is same issue as #17163

**Comment by Dream-Master** [comment]
should be fixed in https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/runs/10825695170

**Comment by SKProCH** [comment]
Also, seems like new frameboxes is one hit break with bare hands. 

Still doesn't test @Dream-Master suggested nightly due to its crashes on startup, which should be fixed already. Waiting till next nightly

**Comment by NotAPenguin0** [comment]
Both the issue in the ticket and the breaking should be fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/3160, please reopen this if not.
