### ISSUE TITLE
Custom names of machines in drone downlink module may reset when exiting world quickly after login

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17323]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Custom machine names in drone downlink module won't reset by any actions.

### The Reality

Custom names of machines in drone downlink module may reset when exiting world quickly after login.
I entered the world, custom machine name is displayed:
![2024-09-13_12 17 20](https://github.com/user-attachments/assets/e2a29a7c-c7bc-4ae6-95e0-1c3b4d2520d3)
I left the world few seconds later and entered again, custom name was reset:
![2024-09-13_12 18 13](https://github.com/user-attachments/assets/4661060d-548c-4dfd-bca7-d1625ee361b7)

### Your Proposal

Fix this bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RealSilverMoon** [comment]
Already fixed in dev. Only need to wait for 2.7.0 and update to it.

**Comment by FireWarrior2** [comment]
> Already fixed in dev. Only need to wait for 2.7.0 and update to it.

@RealSilverMoon that's good but also I want to ask if something was done with perfomance because I linked more than 500 machines to drone center and there is a great fps drop when opening machine list.

**Comment by FireWarrior2** [comment]
@RealSilverMoon not fixed, just did same actions at nightly 690 and names were reset.

**Comment by FireWarrior2** [comment]
I found what's happening.
If leave world when drone downlink modules are disconnected, then when you join world again, they lose custom names.
![2024-11-07_18 42 58](https://github.com/user-attachments/assets/f010299c-4cf2-4f7e-97c6-77cfd4e028d1)
![2024-11-07_18 43 45](https://github.com/user-attachments/assets/47f514c3-691f-4378-a222-efb08226cb82)
[latest.log](https://github.com/user-attachments/files/17664321/latest.log)
