### ISSUE TITLE
Gold dust furnace recipe not working

### ISSUE THREAD

**Issue by Chumgod** [GTNewHorizons/GT-New-Horizons-Modpack#17434]
### Your GTNH Discord Username

randompixl

### Your Pack Version

2.7-beta-java_17-21 Nightly Coremod

### Your Server

SP and Private Server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Cook gold dust into gold in the furnace, turning it into gold ingots

### The Reality

![image](https://github.com/user-attachments/assets/b70b4461-27f8-4a97-95ed-0e7d05a9b97a)
Gold dust doesn't cook.

Extra notes: I have -Dgt.recipebuilder.recipe_collision_check=true enabled on both client and server.
Both impure, pure, and IC2 gold dust smelt into gold ingots, but not regular dust.

### Your Proposal

The gold dust recipe in the furnace is fixed and cooks into gold ingots again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I tried a bunch but I cant reproduce this

**Comment by FourIsTheNumber** [comment]
> Four says they fixed it and its working on the latest version, closed.

I think I said specifically that I didn't fix it 😅 
It seems to be working in that I can't reproduce it (and I could the other day), but I didn't do anything to solve it

**Comment by Derghust** [comment]
I have same issue with enabled `-Dgt.recipebuilder.recipe_collision_check=true`

Most dust processing in furnaces does not work with given arguments.

it seem some recipes stop working in 2.7.0 beta 1 in both case

Such as processing cutting diamonds blocks

![image](https://github.com/user-attachments/assets/ebd1f458-e135-4146-ba13-b666d026b7e6)

![image](https://github.com/user-attachments/assets/34ed2c93-e463-4390-9932-74222ff94b85)

**Comment by pfchrist** [comment]
In 645 (Haven't tried later versions) the hydration cell is also missing a recipe and the extractor recipe that you normally use doesn't work.

![image](https://github.com/user-attachments/assets/4eed59ec-e4b7-4c00-a959-3504120451ef)

![image](https://github.com/user-attachments/assets/f80bc0fb-081a-4a32-a754-419eed3fa572)

Adding here just as another example in case there's some common factor in these missing recipes.

**Comment by FourIsTheNumber** [comment]
> I have same issue with enabled `-Dgt.recipebuilder.recipe_collision_check=true`
> 
> Most dust processing in furnaces does not work with given arguments.
> 
> it seem some recipes stop working in 2.7.0 beta 1 in both case
> 
> Such as processing cutting diamonds blocks
> 
> ![image](https://private-user-images.githubusercontent.com/40358543/371745264-ebd1f458-e135-4146-ba13-b666d026b7e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzU2MjYsIm5iZiI6MTcyNzU3NTMyNiwicGF0aCI6Ii80MDM1ODU0My8zNzE3NDUyNjQtZWJkMWY0NTgtZTEzNS00MTQ2LWJhMTMtYjY2NmQwMjZiN2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyMDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MTAxMDY3YmUzYjVlZmY4NWNhZThlODY4YmVkNmMyZjcyMzllNzBjMDhlMzI5MGMxNzU2NjJkYjQ4ODY4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OMpV6e-4v05YEF_oh7NCshLQVY8aveMvLIa3VK-LDRo)
> 
> ![image](https://private-user-images.githubusercontent.com/40358543/371745284-34ed2c93-e463-4390-9932-74222ff94b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzU2MjYsIm5iZiI6MTcyNzU3NTMyNiwicGF0aCI6Ii80MDM1ODU0My8zNzE3NDUyODQtMzRlZDJjOTMtZTQ2My00MzkwLTk5MzItNzQyMjJmZjk0Yjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyMDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMmYwNDZmODQzM2I1Y2I2YmUyZDU1ODE1MDViZGZmY2I3YjFiNTdmN2M1N2Y1Y2VjNTU4NWQ2ZjE1ZTY5YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2Pxal415XOjQFhaeRgaBuz2xeX13aKbuzAqepdnLqO4)

This is solved

**Comment by lucythebean** [comment]
![2024-10-01_23 49 28](https://github.com/user-attachments/assets/31953ca3-96f7-4501-8119-b108e8c5da5c)
Still getting what I assume is a similar problem in 2.7.0 beta 2, with recipe collision check on. Its also happening with a few other recipes and has been changing on restart (choosing a different item to accept).
