### ISSUE TITLE
The feature that when pressing shift, a data stick shows the scanned item. is not working.

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17446]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.7.0 beta1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

it shows the item like before

### The Reality

The feature that when pressng shift, a data stick shows the scanned item. is not working.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
a little more info here: 
not pressing shift:
![image](https://github.com/user-attachments/assets/4d71a5c3-8450-44f3-8591-f1024589a269)
pressing shift:
![image](https://github.com/user-attachments/assets/c5f33b43-9489-4b18-b19f-d513bed747da)

**Comment by RecursivePineapple** [comment]
It looks like this is fixed in nightly 668:

https://github.com/user-attachments/assets/04a4ae21-271d-404d-b3e1-7a1867f53c34

**Comment by miaowwwwww** [comment]
this is strange, i still have the problem in beta 2, i might need to try a new instance

**Comment by RecursivePineapple** [comment]
@miaowwwwww Can you hold one of the bad data sticks in your hand, run the `/iih` command and put the screenshots here? (make sure to get all of the output, it's pretty big for data sticks)
If you're still seeing it then that means there's a problem somewhere.

**Comment by miaowwwwww** [comment]
![image](https://github.com/user-attachments/assets/ce564390-ce98-4a8b-8c24-9c2bdc63a6c2)
![image](https://github.com/user-attachments/assets/b88b613f-c149-4a3e-94c2-2594c668f6ca)
![image](https://github.com/user-attachments/assets/b0d13de7-60db-427b-8c3a-9d55e5854012)
![image](https://github.com/user-attachments/assets/330f2705-c179-49d3-a2cf-4c650c3e7f6c)
this recipe, this is in sp, newly made stick

**Comment by tommmmmmmmm** [comment]
idk if that is fixed in newer nightlies, but i have the same issue on beta-2 (persisting from earlier on)

[02:50:30] [Client thread/INFO]: [CHAT] == Item info
[02:50:30] [Client thread/INFO]: [CHAT] Unloc.Name:  [gt.metaitem.01.32708]
[02:50:30] [Client thread/INFO]: [CHAT] ItemName:  [gregtech:gt.metaitem.01]
[02:50:30] [Client thread/INFO]: [CHAT] ItemMeta:  [32708]
[02:50:30] [Client thread/INFO]: [CHAT] FluidContainer:  [No fluid container]
[02:50:30] [Client thread/INFO]: [CHAT] ClassName:  [class gregtech.common.items.MetaGeneratedItem01]
[02:50:30] [Client thread/INFO]: [CHAT] ItemNBT:  [{a7:0:{id:7474s,Count:64b,Damage:29975s},a9:0:{id:6077s,Count:4b,Damage:0s},a9:1:{id:7476s,Count:4b,Damage:32120s},a3:0:{id:3779s,Count:16b,Damage:395s},a5:0:{id:7474s,Count:64b,Damage:29982s},a1:0:{id:3779s,Count:16b,Damage:327s},f0:{FluidName:"molten.infinity",Amount:4608},f1:{FluidName:"molten.tritanium",Amount:4608},f2:{FluidName:"molten.mutatedlivingsolder",Amount:4608},f3:{FluidName:"exciteddtrc",Amount:4000},output:{id:2417s,Count:4b,Damage:14s},pages:[0:"Construction plan for 4 Particle Beam Guidance Pipe Casing. Needed EU/t: 31457280 Production time: 60",1:"Input Bus 1: 16 Cosmic Neutronium Frame Box",2:"Input Bus 2: 16 Naquadria Frame Box",3:"Input Bus 3: 16 Naquadah Alloy Frame Box",4:"Input Bus 4: 16 Bedrockium Frame Box",5:"Input Bus 5: 64 Infinity Foil",6:"Input Bus 6: 64 Cosmic Neutronium Foil",7:"Input Bus 7: 64 Superconductor Base UHV Foil",8:"Input Bus 8: 64 Draconium Foil",9:"Input Bus 9: 1 Electric Pump (UEV)",10:"Input Bus 10: 4 Any UEV Circuit
Or 4 Bio Mainframe
Or 4 Optical Computer
Or 4 Exotic Assembly
Or 4 Cosmic Processor",11:"Input Bus 11: 2 Any UIV Circuit
Or 2 Optical Mainframe
Or 2 Exotic Computer
Or 2 Cosmic Assembly
Or 2 Temporally Transcendent Processor",12:"Input Bus 12: 16 Quadruple Infinity Fluid Pipe",13:"Input Hatch 1: 4608L Molten Infinity",14:"Input Hatch 2: 4608L Molten Tritanium",15:"Input Hatch 3: 4608L Mutated Living Solder",16:"Input Hatch 4: 4000L Excited Dimensionally Transcendent Resplendent Catalyst"],a10:3:{id:7476s,Count:2b,Damage:32171s},a10:2:{id:7476s,Count:2b,Damage:32168s},a10:4:{id:7476s,Count:2b,Damage:32174s},a10:1:{id:7476s,Count:2b,Damage:32157s},a10:0:{id:6157s,Count:2b,Damage:0s},a9:2:{id:7476s,Count:4b,Damage:32156s},a9:3:{id:7476s,Count:4b,Damage:32167s},a9:4:{id:7476s,Count:4b,Damage:32170s},10:{id:6157s,Count:2b,Damage:0s},11:{id:2409s,Count:16b,Damage:5255s},author:"Assembling Line Recipe Generator",eu:31457280,0:{id:3779s,Count:16b,Damage:982s},1:{id:3779s,Count:16b,Damage:327s},2:{id:3779s,Count:16b,Damage:325s},3:{id:3779s,Count:16b,Damage:395s},4:{id:7474s,Count:64b,Damage:29397s},5:{id:7474s,Count:64b,Damage:29982s},6:{id:7474s,Count:64b,Damage:29985s},7:{id:7474s,Count:64b,Damage:29975s},lastUpdate:1728087515306L,8:{id:7474s,Count:1b,Damage:32619s},9:{id:6077s,Count:4b,Damage:0s},a11:1,a8:0:{id:7474s,Count:1b,Damage:32619s},a10:5,a4:0:{id:7474s,Count:64b,Damage:29397s},a6:0:{id:7474s,Count:64b,Damage:29985s},a0:0:{id:3779s,Count:16b,Damage:982s},a2:0:{id:3779s,Count:16b,Damage:325s},title:"Particle Beam Guidance Pipe Casing Construction Data",a11:0:{id:2409s,Count:16b,Damage:5255s},a0:1,a1:1,a2:1,a3:1,a4:1,a5:1,a6:1,a7:1,a8:1,Data.Recipe.Hash:"Hash.-373026978",a9:5,time:1200}]
[02:50:42] [Server thread/INFO]: Saving and pausing game...

**Comment by querns** [comment]
This is related to my spraycan; I changed where the Data Stick renderer was stored. Something that might help: create a test world, make a data stick (notch apple is very fast to research), and see if the data stick works as expected.
