### ISSUE TITLE
Wrong Space pumping module mk2 tooltip

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17660]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

nightly 690

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

There will be info about consumption, as other pump modules have:
![image](https://github.com/user-attachments/assets/a13d90e0-639a-407e-9fdb-fdf45b0ac825)

### The Reality

String about different recipes is duplicated:
![image](https://github.com/user-attachments/assets/c5ddf917-f498-49f1-be05-44073155d022)

### Your Proposal

Fix mk2 pumping module tooltip.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
fixed by https://github.com/GTNewHorizons/GTNH-Intergalactic/commit/82b8ae978090f4a73a50d87fa2d079dfd338bc2c

**Comment by FireWarrior2** [comment]
Beta 4 not fixed
![image](https://github.com/user-attachments/assets/241d6160-5b6c-45ec-a7a0-5317ad7fdfff)
