### ISSUE TITLE
[Ingameinfo XML] Numerous isuses after memory optimization update (2.8.14)

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#17772]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.7.0 beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

v2.8.13
![image](https://github.com/user-attachments/assets/b2246025-98db-42af-89e6-8c6b230ce48d)
![image](https://github.com/user-attachments/assets/bbfe8a7b-47d2-4027-9f2b-1ea627977e88)

### The Reality

v2.8.15
![image](https://github.com/user-attachments/assets/7b5c87d9-cabd-4764-a9e2-b4ff45926633)
![image](https://github.com/user-attachments/assets/b04ad580-3c9d-40ac-8682-18cfe862c7b5)

### Your Proposal

After the memory optimization patch for igixml, multiple aspects of the mod rendering broke completely. This includes icon textures, relative icon/text positioning, and status effect textures.

Now v2.8.15 did fix a lot of other issues that came from the patch already, but the above discrepancies are still occurring.

Below is my igixml file that I use (was planning to make a pr for the center chunk icon):

https://gist.github.com/PlayfulPiano/6e3b3ffa774b38aedcd17f6aa699566a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
The icon issues are addressed in https://github.com/GTNewHorizons/InGame-Info-XML/pull/26

I can't really reproduce the positioning issues though, have you changed any other igi settings?
![igi-](https://github.com/user-attachments/assets/266c4dbb-84f8-472d-9ad8-b88396f653d9)
![igi--](https://github.com/user-attachments/assets/499643c6-b8f6-4cc1-8e21-4db9cfaa49a8)

**Comment by PlayfulPiano** [comment]
> The icon issues are addressed in [GTNewHorizons/InGame-Info-XML#26](https://github.com/GTNewHorizons/InGame-Info-XML/pull/26)
> 
> I can't really reproduce the positioning issues though, have you changed any other igi settings? ![igi-](https://private-user-images.githubusercontent.com/127234178/380487235-266c4dbb-84f8-472d-9ad8-b88396f653d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzQ2NTIsIm5iZiI6MTczMDAzNDM1MiwicGF0aCI6Ii8xMjcyMzQxNzgvMzgwNDg3MjM1LTI2NmM0ZGJiLTg0ZjgtNDcyZC05YWQ4LWI4ODM5NmY2NTNkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMzA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGIzZmI4MmM5YWUzMTQ4NzdhM2VlMDE5Mzc3MjQxNjdkNDMxMTdmMzNlNjI1MmM5OGZhMjZkZGMyYzM3NTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XKeAr92MYwKi0ZhOE14-AzNTfAFEHzCRX459nAzCrkg) ![igi--](https://private-user-images.githubusercontent.com/127234178/380487241-499643c6-b8f6-4cc1-8e21-4db9cfaa49a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzQ2NTIsIm5iZiI6MTczMDAzNDM1MiwicGF0aCI6Ii8xMjcyMzQxNzgvMzgwNDg3MjQxLTQ5OTY0M2M2LWI4ZjYtNGNjMS04ZTIxLTRkYjljZmFhNDlhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMzA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGI2Mjg0NTM0N2VlZDFhYTc1NGIzM2RhMDJiZDk0MmI3N2U2N2M4YjY4ZjliOTZmM2I0YTZkYTQwMmUzNzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AipJUT1_lQ4v2Iqhdw2vJTSKw9OLCDKG5TOUATi-vdA)

This is what my actual config is set to for reference:

`# Configuration file

alignment {
    # Offsets for BOTTOMCENTER (X<space>Y).
    S:bottomcenter=0 -45

    # Offsets for BOTTOMLEFT (X<space>Y).
    S:bottomleft=2 -2

    # Offsets for BOTTOMRIGHT (X<space>Y).
    S:bottomright=-2 -15

    # Offsets for MIDDLECENTER (X<space>Y).
    S:middlecenter=0 0

    # Offsets for MIDDLELEFT (X<space>Y).
    S:middleleft=2 0

    # Offsets for MIDDLERIGHT (X<space>Y).
    S:middleright=-2 0

    # Offsets for TOPCENTER (X<space>Y).
    S:topcenter=0 2

    # Offsets for TOPLEFT (X<space>Y).
    S:topleft=2 20

    # Offsets for TOPRIGHT (X<space>Y).
    S:topright=-2 2
}


general {
    # If this is true, it will render the info overlay
    B:ShowHUD=true

    # The interval between file reads for the 'file' tag (in seconds).
    I:fileInterval=5

    # The configuration that should be loaded on startup.
    S:filename=InGameInfo.xml

    # Replace the debug overlay (F3) with the InGameInfoXML overlay.
    B:replaceDebug=false

    # The overlay will be scaled by this amount.(use this one, the other is deprecated)
    I:"scale(new)"=8

    # Display the overlay in chat.
    B:showInChat=true

    # Display the overlay on the player list.
    B:showOnPlayerList=false
}


`

**Comment by PlayfulPiano** [comment]
Tested the new version, icons all work fine now but the weird icon overlap issue is still apparent. Again, only when updating from 2.8.13 to 2.8.16.

Also for the status effects, it appears only one icon shows at a time in .16?
![image](https://github.com/user-attachments/assets/8e8ccaef-2f3c-43aa-a7ef-2d45651be274)
![image](https://github.com/user-attachments/assets/61bbd64d-4a9b-43fc-8373-71f6d151cd49)

**Comment by Lyfts** [comment]
@PlayfulPiano can you give https://github.com/GTNewHorizons/InGame-Info-XML/releases/tag/2.8.17-pre a try?

**Comment by PlayfulPiano** [comment]
> @PlayfulPiano can you give https://github.com/GTNewHorizons/InGame-Info-XML/releases/tag/2.8.17-pre a try?

Just tried it, and everything looks good now. Non-vanilla effects sometimes aren't shown but that was like that prior to the memory optimization patch (and I think it might just be the toughness effect lol).

tysm
![image](https://github.com/user-attachments/assets/2ce98a7c-3818-4389-9265-f0cd1d94e98b)

**Comment by PlayfulPiano** [comment]
well the first line for my name is misaligned but that's much more small beans vs all the other problems lmao

**Comment by PlayfulPiano** [comment]
Actually @Lyfts just developed a crash while playing, although unsure what specifically caused it (I was afk at the time).
[crash-2024-10-27_18.24.22-client.txt](https://github.com/user-attachments/files/17535646/crash-2024-10-27_18.24.22-client.txt)

**Comment by PlayfulPiano** [comment]
ah, appears to have happened when it started raining  https://www.twitch.tv/playfulpiano/clip/SteamyJollyTigerKappaPride-jLVI8riNWBgW44ZG

**Comment by Lyfts** [comment]
@PlayfulPiano most of the issues should (hopefully) be fixed in https://github.com/GTNewHorizons/InGame-Info-XML/releases/tag/2.8.18-pre

**Comment by PlayfulPiano** [comment]
> @PlayfulPiano most of the remaining issues should (hopefully) be fixed in https://github.com/GTNewHorizons/InGame-Info-XML/releases/tag/2.8.18-pre

Looks a lot better, ty
