### ISSUE TITLE
Astral Silver Duplication

### ISSUE THREAD

**Issue by BillyBobJoe12345** [GTNewHorizons/GT-New-Horizons-Modpack#19834]
### Your GTNH Discord Username

fairbanks2126

### Your Pack Version

2.7.4

### Your Server

Private

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Mixing Astral Silver Creates 3 Dust, Centrifuging It Needs 3 Dust

### The Reality

Mixing Astral Silver Creates 3 Dust, Centrifuging It Needs 2 Dust
This Means you can duplicate silver and thaumium by just mixing silver and thaumium in a HV or better mixer and then centrifuging it in any centrifuge

![Image](https://github.com/user-attachments/assets/84898006-c357-4bcf-b40e-6893aa8b5213)

![Image](https://github.com/user-attachments/assets/1580d8db-7017-4ecc-bd08-f64d538f3223)

### Your Proposal

Change the mixing recipe to make 2 Astral Silver Dust 
or
Change the centrifuging recipe to consume 3 Astral Silver Dust

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheEpicGamer274** [comment]
Should be fixed by: https://github.com/GTNewHorizons/GT5-Unofficial/pull/3743

**Comment by BillyBobJoe12345** [comment]
Im not sure it is, that fix is from 4 months ago but I am using 2.7.4 which is from at most 1 month ago
So Unless Im missing something, the fix didnt fix it
