### ISSUE TITLE
ME network does not read another network's storage correctly using more than one storage bus.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#20244]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.7.4

### Your Server

Singleplayer

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Test setup:

![](https://i.imgur.com/6SyYeFA.png)

Red network contains some stored items.

Blue network is trying to read this storage via a storage bus attached to the red network's interface. The storage bus is set to extract only, and is filtered, as I want blue to only see some of the items. With only one storage bus, this works as expected.

However, in my main world, I ran out of filter slots on one storage bus, so I attached another in the same configuration. This I have reproduced above; with only one item filtered per storage bus. I expected the blue network to be able to read all stored items (in this example, both stone and dirt).

### The Reality

Blue network can only see items filtered through one storage bus; in this case only stone. Dirt is invisible, even though it should be accessible through the other bus.

The problem is not resolved even by using another interface on the red network like this:

![](https://i.imgur.com/psEqwMN.png)

In this configuration, the blue network can still only see stone, and not dirt.

### Your Proposal

Blue network should be able to see items filtered through both interfaces.

This could be related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18074 from last year, though theirs uses a more complex configuration.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lc-1337** [comment]
Check on the newest daily, most likely fixed in dev.

**Comment by ddoubleo** [comment]
It is sadly still not fixed on the latest release of AE2 Unofficial as of today

**Comment by lc-1337** [comment]
@ddoubleo working fine on beta-1 https://discord.com/channels/181078474394566657/401118216228831252/1398328810021322904

**Comment by TrubbleAC** [comment]
I'm still having this issue on 2.8.0-beta-1.

**Comment by boubou19** [comment]
@TrubbleAC we are going to need a minimal reproductible setup as @lc-1337 couldn't reproduce it on beta 1

**Comment by lc-1337** [comment]
should work on beta-1 kekw
