### ISSUE TITLE
NEI multiblock structure preview gets corrupted when looking up specific multiblocks

### ISSUE THREAD

**Issue by Miklebe** [GTNewHorizons/GT-New-Horizons-Modpack#20471]
### Your GTNH Discord Username

Mike_be

### Your Pack Version

2.8.0-beta1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When i browse multiblocks, i expect them to show the minimum amount of required hatches and casings.
Example before corruption:
<img width="402" height="452" alt="Image" src="https://github.com/user-attachments/assets/dc2816f5-2d4f-4479-9dfc-f62a79c6b497" />

### The Reality

When looking up specific multiblock, every other one gets completely corrupted and casings get replaced with w/e the hatch/bus preview finds first (most of the time it's input bus steam tier, but depending on restrictions can be maintenance/output hatches).
Usually happens when you look up usage for casings.
Example after corruption:
<img width="396" height="440" alt="Image" src="https://github.com/user-attachments/assets/0e5be495-7b59-4d30-803a-3898fee8bb47" />
After further testing, steel casings could be tied to MAX, UXV and LV hydro turbines/pumps(?), while NEI only has recipes and entries for MV-UV tiers.
https://discord.com/channels/181078474394566657/522098956491030558/1394954250664022036 (videos in beta-testing channel)
But on another run, it happened after i looked at steam separator...? https://discord.com/channels/181078474394566657/522098956491030558/1394956397942149123

While probably good to mention that it seems to not affect certain multis. Mainly: Steam tier, chemplant, elemental duplicator
Actually the behaviour is all over the place, but these are probably the most stable....

### Your Proposal

Fix the renderer.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
Got the problem from looking up usage for the Bronze Casing, so the problem might be with the steam multis, after which it breaks.
Re-tested, everything works fine, the moment i open steam machine preview, casings turn into busses.
Video link: https://discord.com/channels/181078474394566657/522098956491030558/1395034042663047340

**Comment by Miklebe** [comment]
Just to clarify in the ticket itself.
It 100% happens whenever you look up any steam multiblock NEI structure preview. All other multis get corrupted with either Steam Input Bus, or where possible (DT) - ulv hatches.

**Comment by Dream-Master** [comment]
I would be happy if we found a final solution to fix this. So many time it was fixed and broken again.

**Comment by PlayfulPiano** [comment]
<img width="732" height="973" alt="Image" src="https://github.com/user-attachments/assets/b28c395c-1478-48ec-8a2d-687535594a62" />

looks like it's still an issue in beta 4 D:
