### ISSUE TITLE
[NEI/Bartworks] Some OreVein-Generation on Ross128b/Ross128ba are not displayed in NEI

### ISSUE THREAD

**Issue by SST-03** [GTNewHorizons/GT-New-Horizons-Modpack#21083]
### Your Pack Version

2.8.0-beta-3

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

There are 10+8=18 types of Ore-Vein on [Ross128b](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/bartworks/system/oregen/BWWorldGenRoss128b.java)/[Ross128ba](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/bartworks/system/oregen/BWWorldGenRoss128ba.java).

### The Reality
> before [GTNewHorizons/GT5-Unofficial#pull4829](https://github.com/GTNewHorizons/GT5-Unofficial/pull/4829):
> NEI just showed 15 of them, but the missing Ore-Vein still generate on Ross128b/Ross128ba, that means due to some reason > NEI just missed these ore-generation.

now: NEI just showed 17 of them, but the missing Ore-Vein still generate on Ross128b/Ross128ba, ...

### Your Proposal

Fix this.

> List of missing ore-Veins:

> ore.mix.ross128.carbon <- still not display
> ↓after [GTNewHorizons/GT5-Unofficial#pull4829](https://github.com/GTNewHorizons/GT5-Unofficial/pull/4829), fixed and can display↓: 
> ore.mix.ross128ba.CopperSulfits <- display now
> ore.mix.ross128ba.RedZircon <- display now

I guess this problem is from:
ore.mix.ross128ba.CopperSulfits / ore.mix.ross128ba.RedZircon : ross128b has same ore-Vein (ore.mix.ross128.CopperSulfit / ore.mix.ross128.RedZircon)
ore.mix.ross128.carbon : all four ores are not Bart Ores.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@slprime any idea here

**Comment by Yoshy2002** [comment]
fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/4829

**Comment by SST-03** [comment]
@Yoshy2002 Still cannot find ore.mix.ross128.carbon Vein in NEI. REOPEN THIS ISUUE
Reason: pr fixed now"Show same veins in different planet" ,but not including oreVein that all 4 ores are not barkwork ores. [Link](https://github.com/slprime/GT5-Unofficial/blob/16029c2a17a4bf871d997b95f48ca500c26d7bb9/src/main/java/bartworks/neiHandler/OreNEIHandler.java#L178)

**Comment by Yoshy2002** [comment]
Will https://github.com/GTNewHorizons/GT5-Unofficial/pull/4838 completely fix this? Or is further fixing needed

**Comment by SST-03** [comment]
> Will [GTNewHorizons/GT5-Unofficial#4838](https://github.com/GTNewHorizons/GT5-Unofficial/pull/4838) completely fix this? Or is further fixing needed

Yes it will. the main problem is that this pr also add 128b/128ba planet for Harmony eye. (another problem: vein have no English translation, need to change en_US.lang i18n file (OTHER Languages have i18n now) )

**Comment by Yoshy2002** [comment]
Report back when the PR is merged and this issue can be closed then, sorry for the closing, thought linked pr fixed it

**Comment by SST-03** [comment]
> Report back when the PR is merged and this issue can be closed then, sorry for the closing, thought linked pr fixed it

OK.

**Comment by slprime** [comment]
> [@Yoshy2002](https://github.com/Yoshy2002) Still cannot find ore.mix.ross128.carbon Vein in NEI. REOPEN THIS ISUUE Reason: pr fixed now"Show same veins in different planet" ,but not including oreVein that all 4 ores are not barkwork ores. [Link](https://github.com/slprime/GT5-Unofficial/blob/16029c2a17a4bf871d997b95f48ca500c26d7bb9/src/main/java/bartworks/neiHandler/OreNEIHandler.java#L178)

I noticed this problem a little later, but decided not to fix it because there was already a PR that removes this handler

**Comment by SST-03** [comment]
Should be fixed in GTNewHorizons/GT5-Unofficial#4984
