### ISSUE TITLE
unhitable skeletons spawn in oure oil farm (no ai ?)

### ISSUE THREAD

**Issue by Oberon3065** [GTNewHorizons/GT-New-Horizons-Modpack#21394]
### Your GTNH Discord Username

Oberon (Oberon3065)

### Your Pack Version

2.7.4

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

having a oil farm with nether trees .

PS: i dont know the java version of the server if needed i can provide the infromation later (server is at a friends place and i dont have full access )

### The Reality

in the leave blocks are spawning skeletions with wierd buged hitboxes and what looks like no ai.

Image of oure farm with the skeletons
<img width="1497" height="808" alt="Image" src="https://github.com/user-attachments/assets/4d11d1e1-732d-441e-9f52-f65413a85692" />

### Your Proposal

make them killable or remove them with a magnum torch 

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TomassMatos** [comment]
I had the same bug happen to me, manage to get ride of them with "/cofh killall"

**Comment by wlhlm** [comment]
What's an oil farm with nether trees? Please explain the setup.

**Comment by fdsatrew3** [comment]
Its thaumic bases nether trees that replace stone/dirt/any? block below them with netherrack, soulsand or nether quartz. Also they randomly spawn skeletons or other nether creatures (with broken ai like above if they lack space). Later you convert soulsand into oil with gt processing chain

This also happens with end tree from same mod and probably other trees (no idea about their name, check wiki or thaumonicon)

**Comment by Caedis** [comment]
I think this has been fixed already

**Comment by Sharkum** [comment]
I am still facing the same issue in 2.8.4, even after having a chandelier placed near the leaves. These do affect my tps and fps drastically though, the longer the server keeps runing and the number of these skeletons grows
