### ISSUE TITLE
[Hodgepodge] Oversized Chunk at high coordinates after 2.8 upgrade of server (files copied from 2.7.4 into 2.8.0 fresh download)

### ISSUE THREAD

**Issue by PaulM777** [GTNewHorizons/GT-New-Horizons-Modpack#21575]
### Your GTNH Discord Username

Chocobo

### Your Pack Version

2.8.0

### Your Server

87.245.70.196

### Java Version

Java 25

### Type of Server

None

### Your Expectation

The world shouldn't have oversized chunks at locations I've never been to.

### The Reality

Server started to lag. Noticed these issues in the server log:

[21:55:02] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[21:55:05] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (18, 15) - 1593344 bytes used
[21:55:12] [File IO Thread/WARN] [Hodgepodge/]: [Hodg

After the update, strange new chunk files appeared in the world:
<img width="598" height="393" alt="Image" src="https://github.com/user-attachments/assets/2668dcdd-e2ef-4491-a879-4b75ba8349fc" />
<img width="616" height="368" alt="Image" src="https://github.com/user-attachments/assets/b7f717bd-282a-484e-b2c0-8061c3879ba7" />

Here are the attached chunks giving the oversized chunk error
[mca file](https://cdn.discordapp.com/attachments/234936569360809996/1421953097638482051/r.16384.-2.mca?ex=68dae885&is=68d99705&hm=7d1da1698c03d180fd1953ac7647bc44051abc4adc34397a199311960543505f&)

### Your Proposal

I can share the world file, and the logs, but I am not sure how to replicate the issue. I only know that the issue gets worse as time goes on in the world.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PaulM777** [comment]
Here are links to the mca files and the logs:
[r.-49152.-2.mca](https://drive.google.com/file/d/1QhT9kCFo5fh9KZifmmYh-RGpKjfuULAr/view?usp=sharing)
[r.16384.-2.mca](https://drive.google.com/file/d/1R8-rz8P8509j9Yni38NEeLib3hagLons/view?usp=sharing)
[fml-server-latest.log](https://drive.google.com/file/d/1xDDnXa5Lt6Djhu817KI4Sw-aws9O6-1K/view?usp=sharing)

**Comment by pierrei** [comment]
I'm getting the same but for DIM1/r.0.0.mca. I've even tried to remove the file, which in my case triggered the Ender Dragon from coming back. But the file was regenerated and is now growing in size again. I'm also at the same time getting the "Can't keep up" messages and high TPS when the file size increases. Can add logs and more info later if needed.

**Comment by PaulM777** [comment]
I stopped the server, deleted the weird files, and upon reboot they come back:
<img width="622" height="361" alt="Image" src="https://github.com/user-attachments/assets/33c8299f-7a00-4f8f-b24f-84398b12a9cc" />

I then stopped the server and they had data (nobody logged into the server):
<img width="602" height="325" alt="Image" src="https://github.com/user-attachments/assets/e3ddf4ee-2d32-42ac-bee8-81c3cb1e00bf" />

Here are the files:
[mca files.zip](https://drive.google.com/file/d/198ajnJH5WHhPUW7E-mrhWDnseOhonYRz/view?usp=sharing)

Here is the world file:
[world file](https://drive.google.com/file/d/1jGX0mgb3NYXVsYJi0GfK4mhvxYYjaSbw/view?usp=sharing)

**Comment by couref** [comment]
Looking at the contents of `r.-49152.-2.mca` some chunks contain hundreds of thousands of "TileTicks" with the only TileEntities being `GT_TileEntity_Ores`. Couldn't find any TileTicks to compare to in my own region files. Maybe that's useful.

**Comment by boubou19** [comment]
it's probably the result of the ore TEs sometimes spawing with seriously wrong coordinates. We weren't able to find the root cause of this, but it'll probably solve itself the day we stop making ores using a TE.

**Comment by nzeng8** [comment]
I'm also getting the same issue but for `DIM-1/region/r.0.0.mca`. Noticed after TPS dropped to ~7 (from 20) overnight after the update. 

<img width="1394" height="387" alt="Image" src="https://github.com/user-attachments/assets/3b865885-e687-4124-9197-3bfa88a46a41" />

Here's the actual size of the file.

<img width="636" height="77" alt="Image" src="https://github.com/user-attachments/assets/1acbcf31-9d24-4001-9033-0965389960e2" />

Here's the link to the file: [r.0.0.mca](https://drive.proton.me/urls/419H1F9ESM#nD7A1ue9M0zQ)

**Comment by bagr-sus** [comment]
Same thing happened to me - went from 2.8.0 beta 1 to 2.8.0 release. I deleted the offending file and it actually fixed the issue. However, the offending file reappeared after server restart and for some reason keeps getting updated, even though its not loaded. It doesn't appear to be growing in size, atleast not at an alarming rate.

**Comment by SgtMate** [comment]
Not sure if it is related, but on our server we had similar warnings as @nzeng8 also in the nether (DIMM0) near 0,0. I looked into the region file and found that there is a (in my very uneducated opinion) huge amount of "Tile Ticks" entries in some chunks near 0,0. 

<img width="253" height="413" alt="Image" src="https://github.com/user-attachments/assets/77b5c45b-97f5-42dd-9c89-1c9ace3df222" />

Maybe this is also a symptom of #21612 ?

**Comment by MJCaister** [comment]
I think this issue might be the cause of a memory leak I am experiencing after upgrading server from 2.7.4 to 2.8.0.

The hodgepodge errors don't seem to show up until a player joins the server for the first time after a reboot.

My server sits at ~6-7GB memory usage and once the Hodgepodge errors start showing up it slowly goes up to the 12GB max. At the same time the xxxx bytes used in the HP errors keep increasing, up to 11MiB last I checked.

<img width="2592" height="516" alt="Image" src="https://github.com/user-attachments/assets/0192a7f4-7b01-4af5-b983-668c550155c8" />

last 13 hours of fml-latest.log: https://mclo.gs/52SBiiC

Server is on Java 21.

**Comment by SgtMate** [comment]
@MJCaister have you tried `/gamerule doFireTick false` ? for me it helped reducing the impact of another isssue that might be related to this.

**Comment by Lucas-Dreveck** [comment]
I believe that something related is happening to me too.
I'm running two GT:NH 2.8.0 servers on Java 25. The fresh server (created yesterday) immediately suffers from the "Can't keep up!" warnings, leading to a steady increase in RAM usage until the server crashes. The older server (approx. 50 hours, migrated from 2.7.4) only started showing this exact behavior recently, specifically when I started exploring new chunks.

(The migrated server's world history: SP 2.7.4 -> Server 2.7.4 -> Server 2.8.0. I don't think this is relevant.)

On the migrated server, I installed Spark, downgraded the server's Java from 25 to 21, and ran a profiler. The results seem inconclusive to me: https://spark.lucko.me/r9DHPEpUGK

**Comment by BrixTM** [comment]
Adding into this I've been experiencing the same issue, server CPU and memory usage steadily climbs, to get around this I've limitted the servers total CPU capacity to prevent it from locking up and scheduled a restart every day. 

<img width="887" height="278" alt="Image" src="https://github.com/user-attachments/assets/df31a7fa-e9ed-416a-a64c-c281be789418" />

<img width="455" height="653" alt="Image" src="https://github.com/user-attachments/assets/7d4d2c64-241e-40e5-87a1-ae4ceb09f2b4" />


We can also see the file size of the offending MCA file is substantially higher than any others.

<img width="669" height="174" alt="Image" src="https://github.com/user-attachments/assets/c9a9aac6-17f2-4b6a-8222-5b694eb71ce6" />


Navigating to the faulting chunk and I've found a very oddly generated chunk that was NOT like this prior to updating the pack. This was previously just a normal chunk of the end island. This chunk had nothing in it, was not being force loaded and had been loaded in the past, it is not a new chunk.

<img width="2079" height="1256" alt="Image" src="https://github.com/user-attachments/assets/f43bf6b3-f553-4f0b-bba7-4d33a4fb7184" />

<img width="1194" height="780" alt="Image" src="https://github.com/user-attachments/assets/bddbba38-e4e3-4684-b599-6f53d2b12a5a" />


The chunk itself seems like it is a normal chunk however near the very bottom of the chunk there appears to be a block of lava that has appeared in the corner of the chunk, other thank that it all seems fine aside from the strange holes. I'll remove the block of lava and see if that does anything, it was all source blocks of lava about 5 blocks tall.

<img width="2246" height="1167" alt="Image" src="https://github.com/user-attachments/assets/5ce0487d-9778-4555-81b1-45374fd4acfd" />

**Comment by asquared31415** [comment]
I also have this issue after migrating to 2.8.0, at chunk 1,0 in the end dimension.  No weird lava sources though, just some swiss cheese that i think is new, and massive region file with 100k+ TileTicks.

**Comment by SgtMate** [comment]
@asquared31415 Yes i described the same issue in #21673 Im not sure if this is the same issue the creator of this ticket saw though.
Maybe we have 2 different problems here.

**Comment by PaulM777** [comment]
I see this issue as well. I left the server running overnight and it eventually ran out of memory:

```
[07:56:54] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[07:56:56] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1638400 bytes used
[07:57:01] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (18, 15) - 2019328 bytes used
[07:57:06] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (18, 14) - 1671168 bytes used
[07:57:11] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (19, 15) - 2392064 bytes used
[07:57:12] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1638400 bytes used
[07:57:18] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1638400 bytes used
[07:57:20] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (20, 16) - 2940928 bytes used
[07:57:21] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1638400 bytes used
[07:57:23] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (19, 16) - 2314240 bytes used
[07:57:25] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (19, 17) - 2048000 bytes used
[07:57:28] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1638400 bytes used
[07:57:29] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1642496 bytes used
[07:57:32] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.-49152.-2.mca at (20, 15) - 1527808 bytes used
[07:57:33] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.-49152.-2.mca at (21, 15) - 1867776 bytes used
[07:57:35] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.-49152.-2.mca at (21, 16) - 2101248 bytes used
[07:57:36] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.-49152.-2.mca at (20, 16) - 3014656 bytes used
[07:57:36] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.-49152.-2.mca at (19, 16) - 1916928 bytes used
[07:57:44] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1638400 bytes used
[07:57:47] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[07:57:49] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\DIM-1\region\r.-1.0.mca at (28, 3) - 1638400 bytes used
[07:57:53] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (18, 15) - 2023424 bytes used
[07:57:56] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (18, 14) - 1671168 bytes used
[07:57:58] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.16384.-2.mca at (19, 15) - 2396160 bytes used
[08:03:23] [Thread-9/INFO] [STDERR/BuildCraft|Robotics]: [java.lang.Throwable$WrappedPrintStream:println:790]: java.lang.OutOfMemoryError: Java heap space
```

**Comment by SgtMate** [comment]
@PaulM777 can you see if you have swiss cheese in the end?

**Comment by PaulM777** [comment]
In my case is Dim-1, the Nether. I went to the chunk and didnt notice anything weird. It was chunkloaded however so I deleted all my chunkloads and reloaded only my base. Will see if it makes a difference.

**Comment by flamingowrangler2869** [comment]
I have this exact same issue, end dimension, lava source and all. The swiss cheese chunk is 0,0 and the lava source is at 0,4,0. It was not chunkloaded or claimed. 
However, the error message bounces around between 4,28, 5,28, and 3,29 randomly, and also claims the error is in region r.0.-1, which doesnt even include any of the aforementioned chunks, and opis doesnt show anything unusual

<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/e1543b98-a1f2-408a-adcb-e7791368ab03" />

**Comment by mnsnownutt** [comment]
Confirm, did not get the lava, but these particle effects kept spamming in the affected chunk in the end.  Get the same warning messages in hodgepodge regarding oversized chunk and the server runs out of memory eventually, need to restart it roughly every 45-60 minutes.

EDIT - I claimed the chunk and chunkloaded it through server utilities and after doing that I no longer got the messages regarding oversized chunks and did not need to restart the server after letting it run about 75 minutes.  Plan on seeing if it can go longer than that and if unclaiming the chunk brings back the issue.

<img width="1736" height="1027" alt="Image" src="https://github.com/user-attachments/assets/b303475f-8ae1-4cc5-9c5e-bb3181865599" />

**Comment by SgtMate** [comment]
Also had no lava but some particles in the end, they were so uncommen though that I thougth my eyes are tricking me. They look like whats shown on the screenshot though.

**Comment by leumasme** [comment]
This is happening since 2.8, first mention in the discord on date 21.9., 6 mentions since then.

We are also seeing a swiss cheese chunk with lava at 0/0

From parsing the problematic region file, it seems like millions of queued tile updates for block id 1384 are getting accumulated at chunk 0/0

This is causing huge server lag. I think a temporary workaround should be keeping the end chunk 0/0 force-loaded so the queued tile updates can execute instead of piling up.
```
Total TileTicks: 3,858,615

First 10 scheduled block updates:
------------------------------------------------------------
#0: x=Int(4), y=Int(78), z=Int(8), block_id=Int(1384), time=Int(-6985535), priority=Int(0)
#1: x=Int(8), y=Int(66), z=Int(11), block_id=Int(1384), time=Int(-6985535), priority=Int(0)
#2: x=Int(6), y=Int(66), z=Int(11), block_id=Int(1384), time=Int(-6985535), priority=Int(0)
#3: x=Int(8), y=Int(95), z=Int(8), block_id=Int(1384), time=Int(-6985535), priority=Int(0)
#4: x=Int(14), y=Int(74), z=Int(3), block_id=Int(1384), time=Int(-6985534), priority=Int(0)
#5: x=Int(6), y=Int(24), z=Int(13), block_id=Int(1384), time=Int(-6985534), priority=Int(0)
#6: x=Int(4), y=Int(94), z=Int(10), block_id=Int(1384), time=Int(-6985534), priority=Int(0)
#7: x=Int(5), y=Int(95), z=Int(10), block_id=Int(1384), time=Int(-6985534), priority=Int(0)
#8: x=Int(5), y=Int(94), z=Int(10), block_id=Int(1384), time=Int(-6985534), priority=Int(0)
#9: x=Int(7), y=Int(66), z=Int(13), block_id=Int(1384), time=Int(-6985534), priority=Int(0)
```

Script to extract the region file and print the above: ^

<details>

<summary>python3 script depending on nbtlib</summary>

```py
import struct
import zlib
from nbtlib import nbt
import tempfile
import os

print("Unzipping, this will take a minute")

# Read chunk (0,0) from region file
with open('./r.0.0.mca', 'rb') as f:
    # Read location of chunk 0 (first 4 bytes of header)
    offset_bytes = f.read(3)
    sector_count = f.read(1)[0]
    offset = int.from_bytes(offset_bytes, 'big')
    
    # Seek to chunk data
    f.seek(offset * 4096)
    
    # Read chunk
    length = struct.unpack('>I', f.read(4))[0]
    compression_type = f.read(1)[0]
    compressed_data = f.read(length - 1)

# Decompress
nbt_data = zlib.decompress(compressed_data)

# Parse NBT
with tempfile.NamedTemporaryFile(mode='wb', delete=False, suffix='.nbt') as f:
    temp_path = f.name
    f.write(nbt_data)

try:
    nbt_file = nbt.load(temp_path)
    tile_ticks = nbt_file['Level']['TileTicks']
    
    print(f"Total TileTicks: {len(tile_ticks):,}\n")
    print("First 10 scheduled block updates:")
    print("-" * 60)
    
    for i in range(min(10, len(tile_ticks))):
        tick = tile_ticks[i]
        print(f"#{i}: x={tick['x']}, y={tick['y']}, z={tick['z']}, "
              f"block_id={tick['i']}, time={tick['t']}, priority={tick['p']}")
    
finally:
    os.unlink(temp_path)
```

</details>

**Comment by SgtMate** [comment]
Thanks for the script. I've ran it against my r.0.0.mca and got the following result:

```
Unzipping, this will take a minute
Total TileTicks: 6,100,286

First 10 scheduled block updates:
------------------------------------------------------------
#0: x=Int(13), y=Int(47), z=Int(4), block_id=Int(1411), time=Int(-8651791), priority=Int(0)
#1: x=Int(6), y=Int(81), z=Int(11), block_id=Int(1411), time=Int(-8651782), priority=Int(0)
#2: x=Int(6), y=Int(68), z=Int(2), block_id=Int(1411), time=Int(-8651757), priority=Int(0)
#3: x=Int(13), y=Int(47), z=Int(4), block_id=Int(1411), time=Int(-8651677), priority=Int(0)
#4: x=Int(6), y=Int(81), z=Int(11), block_id=Int(1411), time=Int(-8651668), priority=Int(0)
#5: x=Int(13), y=Int(47), z=Int(4), block_id=Int(1411), time=Int(-8651667), priority=Int(0)
#6: x=Int(13), y=Int(47), z=Int(4), block_id=Int(1411), time=Int(-8651662), priority=Int(0)
#7: x=Int(6), y=Int(81), z=Int(11), block_id=Int(1411), time=Int(-8651658), priority=Int(0)
#8: x=Int(6), y=Int(81), z=Int(11), block_id=Int(1411), time=Int(-8651653), priority=Int(0)
#9: x=Int(5), y=Int(36), z=Int(11), block_id=Int(1411), time=Int(-8651647), priority=Int(0)
```

The block id is different. Is there a way to translate it into what block that is?

**Comment by DarkShadow44** [comment]
There's duplicate ticks there, that should be impossible. Looks like something is going horribly wrong here. Would need to reproduce the issue myself to know more though...

**Comment by SgtMate** [comment]
Hi, I have uploaded the [serve files](https://1drv.ms/u/c/1d2434bab62286d9/EQgh1RFeIdNBqwTYQ7O2GZYBrXediWTyz4A8jucHr_ZnFQ?e=HXGvJu), feel free to have a look.

**Comment by DarkShadow44** [comment]
Thanks, I will take a look when I got my PC working again, sometime next week.

**Comment by MJCaister** [comment]
Adding mine as well. Mine seems to be pointing to a HEE block ID.

I'll note as well that I have broken every single block in chunk 0, 0 and I am still getting the errors. Occasionally also in chunk 0, 1.

[World download](https://1drv.ms/u/c/bd08d27ea7b60a89/EURmm0WD9qhNtOh8JWsemGcB61w6tUs5vrpAdccUhaYIRQ?e=9II6yV)

```
Unzipping, this will take a minute
Total TileTicks: 1,874,388

First 10 scheduled block updates:
------------------------------------------------------------
#0: x=Int(15), y=Int(25), z=Int(7), block_id=Int(1384), time=Int(-9848576), priority=Int(0)
#1: x=Int(14), y=Int(25), z=Int(6), block_id=Int(1384), time=Int(-9848576), priority=Int(0)
#2: x=Int(15), y=Int(100), z=Int(4), block_id=Int(1384), time=Int(-9848574), priority=Int(0)
#3: x=Int(14), y=Int(117), z=Int(10), block_id=Int(1384), time=Int(-9848574), priority=Int(0)
#4: x=Int(14), y=Int(118), z=Int(11), block_id=Int(1384), time=Int(-9848574), priority=Int(0)
#5: x=Int(15), y=Int(122), z=Int(1), block_id=Int(1384), time=Int(-9848574), priority=Int(0)
#6: x=Int(12), y=Int(42), z=Int(3), block_id=Int(1384), time=Int(-9848572), priority=Int(0)
#7: x=Int(9), y=Int(7), z=Int(13), block_id=Int(1384), time=Int(-9848572), priority=Int(0)
#8: x=Int(8), y=Int(8), z=Int(13), block_id=Int(1384), time=Int(-9848572), priority=Int(0)
#9: x=Int(9), y=Int(6), z=Int(13), block_id=Int(1384), time=Int(-9848572), priority=Int(0)
```

**Comment by leumasme** [comment]
The block that seems to be spammed most at 0/0 is `HardcoreEnderExpansion:corrupted_energy_low`.  
[BlockCorruptedEnergy.java](https://github.com/GTNewHorizons/Hardcore-Ender-Expansion/blob/bb21ab45aec18c67613135a07e2f286de38f7173/src/main/java/chylex/hee/block/BlockCorruptedEnergy.java)

It makes sense that a few of the updates propagate to adjacent chunks as the block logic does that.

**Comment by PaulM777** [comment]
I created a new world and ran into the same issue:
[19:25:28] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[19:25:31] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (8, 21) - 8007680 bytes used
[19:25:32] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (7, 23) - 3977216 bytes used
[19:25:34] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (8, 21) - 8007680 bytes used
[19:25:35] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (6, 23) - 2134016 bytes used
[19:26:13] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[19:26:15] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (7, 23) - 3977216 bytes used
[19:26:17] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (8, 21) - 8011776 bytes used
[19:26:19] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (6, 23) - 2134016 bytes used
[19:26:21] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (7, 23) - 3977216 bytes used
[19:26:58] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[19:27:00] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (7, 23) - 3977216 bytes used
[19:27:02] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (8, 21) - 8011776 bytes used
[19:27:03] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (6, 23) - 2134016 bytes used
[19:27:04] [File IO Thread/WARN] [Hodgepodge/]: [Hodgepodge] Oversized Chunk in .\World\region\r.2.-1.mca at (7, 23) - 3977216 bytes used

And insane amount of tileticks:
<img width="254" height="413" alt="Image" src="https://github.com/user-attachments/assets/ff736e5e-d118-43cd-84a6-be71ac05b347" />

[r.2.-1.zip](https://github.com/user-attachments/files/22750812/r.2.-1.zip)

I used the python script above and found that there are a massive amount of duplicate tileticks on gravel blocks:

Chunk (8,21) — Total TileTicks: 2,647,472
TileTicks with count > 1: 883
x=Int(1158), y=Int(57), z=Int(-176), block_id=Int(13), count=3326
x=Int(1157), y=Int(57), z=Int(-176), block_id=Int(13), count=3326
x=Int(1157), y=Int(58), z=Int(-176), block_id=Int(13), count=3326
x=Int(1155), y=Int(58), z=Int(-176), block_id=Int(13), count=3326
x=Int(1156), y=Int(57), z=Int(-176), block_id=Int(13), count=3326
x=Int(1156), y=Int(58), z=Int(-176), block_id=Int(13), count=3326
x=Int(1152), y=Int(57), z=Int(-176), block_id=Int(13), count=3326
x=Int(1152), y=Int(58), z=Int(-176), block_id=Int(13), count=3326
x=Int(1152), y=Int(58), z=Int(-175), block_id=Int(13), count=3326
x=Int(1153), y=Int(58), z=Int(-176), block_id=Int(13), count=3326
x=Int(1155), y=Int(18), z=Int(-170), block_id=Int(13), count=3326
x=Int(1154), y=Int(18), z=Int(-171), block_id=Int(13), count=3326
x=Int(1154), y=Int(19), z=Int(-171), block_id=Int(13), count=3326
x=Int(1152), y=Int(17), z=Int(-169), block_id=Int(13), count=3326
x=Int(1152), y=Int(20), z=Int(-171), block_id=Int(13), count=3326
x=Int(1152), y=Int(20), z=Int(-168), block_id=Int(13), count=3326
x=Int(1153), y=Int(20), z=Int(-171), block_id=Int(13), count=3326
x=Int(1152), y=Int(21), z=Int(-170), block_id=Int(13), count=3326

**Comment by DarkShadow44** [comment]
Could I bother you to test [this PR?](https://github.com/GTNewHorizons/Hodgepodge/pull/642/)  ([Download is here at the bottom](https://github.com/GTNewHorizons/Hodgepodge/actions/runs/18324528858))
With Simulation Distance enabled in HodgePodge and without any other workarounds, of course.

If my analysis of the error is correct, if a chunk is often loaded / unloaded the number of ticks creeps up until the server is restarted. This PR should fix that.

**Comment by SgtMate** [comment]
@DarkShadow44 just copy all jars to the mods folder or just one of them?

**Comment by MJCaister** [comment]
> [@DarkShadow44](https://github.com/DarkShadow44) just copy all jars to the mods folder or just one of them?

I believe you need to use the one that doesn't end in `dev` or `sources`.

I'm also going to test this myself.

**Comment by HinesW57** [comment]
Using this PR I ran the server over night and did not experience any oversized chunk issues.

**Comment by pierrei** [comment]
That's very promising. Also running the change now on our server and will report back tomorrow 👍

**Comment by Cozzmolot** [comment]
Starting it on my server now as well.  Will be able to report back within ~8 hours.  Was normally noticeable by then.

**Comment by SgtMate** [comment]
Have tested it now for the past 12h. It works great, so far no Oversized Chunk messages in the logs. RAM usage is also lower than before.

**Comment by philiannacone350** [comment]
I downloaded the fix and it's working really well for me too!

No reports of oversized chunks in around 15 hours.

**Comment by MJCaister** [comment]
I'm now sitting at 25 hours uptime and no oversized chunk errors and only up to 8GB of memory usage.

**Comment by PaulM777** [comment]
It solved the problem with oversized chunks, but i still have the strange issue with weird .mca files in my world. They appear to be harmless though, so i may raise a separate ticket for that. @DarkShadow44 Thank you for the fix!

<img width="939" height="634" alt="Image" src="https://github.com/user-attachments/assets/38b9806a-5b09-4462-963d-25ee5fda4c1e" />

**Comment by pierrei** [comment]
For us the oversized chunk message is also gone and CPU + memory usage is good - amazing!

**Comment by DarkShadow44** [comment]
> It solved the problem with oversized chunks, but i still have the strange issue with weird .mca files in my world. They appear to be harmless though, so i may raise a separate ticket for that. [@DarkShadow44](https://github.com/DarkShadow44) Thank you for the fix!

Separate issue seems a good idea. Does disabling Simulation Distance workaround those weird mca files? If you find a way to reproduce I can take a look!

**Comment by KirbYyY1998** [comment]
Have the exact same issue on my server, tps just goes to hell after around 16-20h of runtime, I deployed the above PR and will update if that fixes the issues.

EDIT: Server has been running stable since with no tps issues at all.

**Comment by Gandoraffu** [comment]
PR solved the memory and TPS issues on my SP world (30+hr uptime). The already generated oversized .mca files don't shrink on their own though. Thanks a lot for the work, the pack is playable again! :D

**Comment by Pockyninja** [comment]
I been having this issue on my single player world, but I don't really understand what you all are doing to fix this since I don't really mess with any files or know how this works. Can you please tell me a step by step guide on how to fix it. Thank you very much

**Comment by PaulM777** [comment]
> I been having this issue on my single player world, but I don't really understand what you all are doing to fix this since I don't really mess with any files or know how this works. Can you please tell me a step by step guide on how to fix it. Thank you very much

@Pockyninja Inside your mods folder there will be a "hodgepodge-2.6.108.jar" file. You move this file somewhere else and replace it with the file named "hodgepodge-2.7.2-git.1+ec0e1a37b4-dirty.jar" which you can extract from this zip file downloaded from the PR [https://github.com/GTNewHorizons/Hodgepodge/actions/runs/18324528858/artifacts/4207897958](https://github.com/GTNewHorizons/Hodgepodge/actions/runs/18324528858/artifacts/4207897958)

**Comment by Pockyninja** [comment]
Thank you very much for the run down. It seems to be working well.

**Comment by xDParis64** [comment]
I also had this issue on my Java 17 2.8.0 Server - removing the old Hodgepodge jar with the dirty one from the PR has seemingly resolved it and no longer is dropping the TPS.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Hodgepodge/pull/642

**Comment by Glease** [comment]
Meanwhile could also try https://github.com/GTNewHorizons/Hardcore-Ender-Expansion/pull/32 as a fix. I'm unaware of this issue while cooking up the HEE bandaid fix but in retrospect these two seems to be connected

**Comment by ebmusicman84** [comment]
I'm not getting any lag, oversized chunk errors, or building up a crazy amount of tile ticks, but I am still getting swiss cheese at 0,0 in  the end even with both addSimulationDistance=false and hodgepodge-2.7.2-git.1+ec0e1a37b4-dirty.jar installed.  Not sure if this is related or some other issue.

Further update: I removed Hodgepodge all together and am still getting swiss cheese.  I replace the entire chunk with fresh endstone and look inside with spectator, I can see it happening in real time.

Second update: Issue persists in 2.8.1.  Brand new world and the end is swiss cheesing at 0,0 even before the dragon is killed.  I don't get any lava or see any lag / errors.  Just the swiss cheese.

**Comment by SgtMate** [comment]
Hey, does somebody know if the issue is fixed in 2.8.1? I dont wanna update until this is fixed in a release.

**Comment by sisyphussy** [comment]
FIxed in 2.8.1

**Comment by ebmusicman84** [comment]
> FIxed in 2.8.1

Should I open a separate issue for the issue I'm seeing then?  Cause that I definitely not fixed in 2.8.1.  The swiss cheese is happening even on a newly created world while the dragon is still alive.

**Comment by sisyphussy** [comment]
sure
