### ISSUE TITLE
Mars unreachable with ANY Rocket

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#2158]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Flew in T2 Rocket to Space, expected to be able to enter Mars, Phobos, Deimos. Re-Tested with T6 Rocket.
#
#### What happend instead? (Attach screenshots if needed)
Could NOT enter Mars, but could enter Phobos and Deimos with T2 and T6.
#
#### What do you suggest instead/what changes do you propose?
Enter Mars with T2.

**Comment by timothy1601** [comment]
Works for me fine on the same Version on Myftb.de

**Comment by Dream-Master** [comment]
Maybe mars world folder are brocken on delta

**Comment by Dream-Master** [comment]
Seems to be a issue on delta only.

**Comment by Bryfer** [comment]
this issue seems to be on Epsilon aswell, only tested with t2 rocket tho.
unable to gets to mars, but moons of mars works properly

**Comment by Dream-Master** [comment]
We wiped all dims the last update. I guessed it was solved?

**Comment by tranceplanet** [comment]
This issue still exists today on Epsilon.  Just made a T2 rocket.

Mars says Tier 2 on the galactic map but it's **red** and can't be clicked.

I managed to get to Phobos, didn't check Deimos but I assume its the same as Phobos.  Only appears to be Mars thats bugged.

**Comment by Dream-Master** [comment]
Yea i very old issue. IDK no wipe and nothing helps. Maybe someone have a idea here.

**Comment by Dream-Master** [comment]
Problem still exists idk why.

**Comment by Dream-Master** [comment]
maybe we need to change id to test if another id works.

**Comment by Prometheus0000** [comment]
Is this still an issue?

**Comment by Dream-Master** [comment]
Yes it is and idk how to fix. We have Gc forked maybe you can have a look @glowredman ?

**Comment by Prometheus0000** [comment]
Keep in mind that this only seems to affect mp? Are other unofficial servers affected?

**Comment by Dream-Master** [comment]
I need to ask on the other servers

**Comment by boubou19** [comment]
we bypassed the issue on the officials with stargates so if it happens only on the officials it can be closed
