### ISSUE TITLE
Sometimes player cannot open Wireless Ultra Terminal in baubles

### ISSUE THREAD

**Issue by SST-03** [GTNewHorizons/GT-New-Horizons-Modpack#21603]
### Your Pack Version

2.8.0

### Your Server

Private Server

### Java Version

Java 25

### Type of Server

None

### Your Expectation

Open Wireless Ultra Terminal in baubles by using keybind

### The Reality

Sometimes I Cannot open it by using keybind.
However if press E and press the bauble button, then player can open Wireless Ultra Terminal normally.

### Your Proposal

fix this

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by combusterf** [comment]
Probably fixed with https://github.com/GTNewHorizons/Baubles-Expanded/pull/15

**Comment by shimmeringcircuits** [comment]
> Probably fixed with [GTNewHorizons/Baubles-Expanded#15](https://github.com/GTNewHorizons/Baubles-Expanded/pull/15)

This is not fixed and is present in my private server, version 2.8.1. Issue is still present with the most recent prerelease jar, as well.

**Comment by retarepo** [comment]
Just updated from 2.7 to 2.8.4 and now I am encountering the same issue.

The problem only occurs when there are two players on the server, always the last player to join can use the terminal and the other not. If the first relogs, they switch places. I can not test for more then two players.

I also noticed that the keybind works, when the terminal is somewhere in the normal inventory (so not in bauble).
