### ISSUE TITLE
Void Miner not giving correct Stone Type

### ISSUE THREAD

**Issue by jude123412** [GTNewHorizons/GT-New-Horizons-Modpack#21921]
### Your GTNH Discord Username

jude123412

### Your Pack Version

Experimental 2025-10-10+32

### Your Server

SP

### Java Version

Java 25

### Type of Server

None

### Your Expectation

Void Miners should give the relevant planets stone type ores.

### The Reality

Ores given by Void Miners on Galacticraft, Galaxyspace and Amun Ra give the default stone type ores.

### Your Proposal

Void Miners should give the stone type relevant to the planet they are build on. 

For something like the Overworld or the Twilight Forest (when there are more than one stone type), the Void Miner should have something like an 80% chance to give the default stone type and a 20% chance divided by the amount of different stone types to give the extra stone types.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PLASMAchicken** [comment]
Assuming fixed with latest Version. Feel free to comment with more Info to reopen the Issue.

**Comment by jude123412** [comment]
So currently the issue is still present. I'll have a look to see if I can fix it.
