### ISSUE TITLE
Baubles disappear when another player joins/leaves the game

### ISSUE THREAD

**Issue by Iamworking12** [GTNewHorizons/GT-New-Horizons-Modpack#21957]
### Your GTNH Discord Username

iamworking

### Your Pack Version

experimental 35

### Your Server

private server

### Java Version

Java 25

### Type of Server

Vanilla Forge

### Your Expectation

Baubles will work fine all the time.

### The Reality

When someone joins or leaves, my own baubles cease to function (power goggles/ terminal / magnet).
Opening baubles menu fixes the issue.

### Your Proposal

Fix.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PLASMAchicken** [comment]
Assuming fixed with latest Version. Feel free to comment with more Info to reopen the Issue.

**Comment by WowSuchRicky** [comment]
@PLASMAchicken  This is still an issue for me on 2.8.4, haven't tested on daily. Any specific logs/etc I can provide to help triage? I don't actually see anything of note in the logs, but ever since we started playing, when my friend connects my holo glasses stop working and I cannot use my universal terminal via hotkey anymore until I re-equip both of these items

**Comment by PLASMAchicken** [comment]
@WowSuchRicky test it in latest daily then .....
