### ISSUE TITLE
essentia terminals not showing aspects

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#22141]
### Your GTNH Discord Username

MIAOW

### Your Pack Version

daily 197

### Your Server

iota

### Java Version

Java 25

### Type of Server

None

### Your Expectation

<img width="790" height="425" alt="Image" src="https://github.com/user-attachments/assets/e72919ee-a578-4d5d-9730-909d8fd8dfa5" />

### The Reality

tested with both in world and wireless versions, essentias are a no show

<img width="483" height="231" alt="Image" src="https://github.com/user-attachments/assets/be9ac8fb-a0f4-460d-80f4-2dc6649d644a" />

<img width="672" height="507" alt="Image" src="https://github.com/user-attachments/assets/3ab52062-4661-486d-a294-dc7551f1c432" />

as u can see we have essentia in AE

### Your Proposal

fix

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lc-1337** [comment]
try put essentia from phial then reboot world

**Comment by Celarious** [comment]
I've noticed the same on 2.8.1 stable with an in-world essentia terminal and a wireless fluid terminal, sometimes the essentia/fluids simply don't show up and I need to switch universal terminal tabs or close/re-open the terminal GUI a few times for them to populate properly. Devices were always online and had channels along with all the cells, so seems to be a UI bug

**Comment by Celarious** [comment]
Just an update: Seems like the system can't use the essentia either, I tried to do infusion with some essentia in my system and it acts as if it isn't there. I checked the cells and they're online and the essentia is in them, but the terminal shows nothing, a client reboot didn't help either, had an infusion fail because of it
Bug is extremely irritating

**Comment by seramyu** [comment]
My server runs on Java Version "21.0.8" 2025-07-15 LTS. I experience the same issue as described above. Whenever a craft is requested that needs essentia the ME-System does not seem to be able to locate it despite the system being chunkloaded and having energy. Checking the terminal shows a blank one. 
Only know "fix" so far is to just wrench the Terminal off the cable and attach it which then resumes any open crafts and shows the essentia again.

**Comment by abitaredomdepo** [comment]
<img width="1016" height="1011" alt="Image" src="https://github.com/user-attachments/assets/9a434404-e421-4ad8-9f9a-4fc5bc8aaae1" />
temporary solution, no thanks

**Comment by ebmusicman84** [comment]
This issue is persistent and game breaking in 2.8.1.

**Comment by Demosthenexx** [comment]
Having the same problem in 2.8.1. I have a row of alembics providing essentia that passively refill. Systems which do crafting use the original amount, but are not aware of the alembic refilling. It's like when the network boots, it sees essentia normally. When that is used for crafting, the storage busses are not seeing the current content.

**Comment by PLASMAchicken** [comment]
Pretty sure this is fixed in 2.8.3 can you test @Demosthenexx  @ebmusicman84 ?

**Comment by Demosthenexx** [comment]
> Pretty sure this is fixed in 2.8.3 can you test [@Demosthenexx](https://github.com/Demosthenexx) [@ebmusicman84](https://github.com/ebmusicman84) ?

I just updated our TEST and production servers to 2.8.3. It is not fixed.

I have a row of alembics passively filling. 32 of an aspect in it. If I craft with the Essentia Provider, the amount of essentia goes to 0 and does not update when the alembics refill. If I bust my Essentia Terminal and replace it, the network updates briefly with the right amount. If I power cycle the whole ME network, it updates briefly with the right amount.

It's completely crippled automatic alchemy.

**Comment by Demosthenexx** [comment]
Tried outputting to jars instead, and it still thinks there is nothing in the network.

**Comment by Demosthenexx** [comment]
Actually, it looks like it updates dynamically while adding and removing essentia. If the amount hits ZERO, then it never updates again.

**Comment by PLASMAchicken** [comment]
> Actually, it looks like it updates dynamically while adding and removing essentia. If the amount hits ZERO, then it never updates again.

Is this related to this issue where it doesnt show any at all, or something specific?

**Comment by Demosthenexx** [comment]
> > Actually, it looks like it updates dynamically while adding and removing essentia. If the amount hits ZERO, then it never updates again.
> 
> Is this related to this issue where it doesnt show any at all, or something specific?

It shows some at intermittent times. Depending on what's been used. The amount in the Essentia Terminal doesn't match what is present in the jars attached to the essentia storage busses.

**Comment by Demosthenexx** [comment]
If I break the Essentia Terminal, and place it again, suddenly all the values are correct. This must be triggering some form of network update.

**Comment by Demosthenexx** [comment]
As a workaround I have setup an ME inverted toggle cable against my Essentia Terminal, and a redstone clock breaking the connection every 10 seconds.

**Comment by ebmusicman84** [comment]
This was resolved for me in 2.8.2 by #22237
