### ISSUE TITLE
Twilight Forest Naga causes fps drops when looked at

### ISSUE THREAD

**Issue by BadsyEdgecat** [GTNewHorizons/GT-New-Horizons-Modpack#22285]
### Your GTNH Discord Username

Badsy the Edgecat (She/her)

### Your Pack Version

2.8.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I look at the Naga in its structure, or its NEI droplist, and the fps stays stable.

### The Reality

When the Naga is onscreen, either in the game world or in NEI, the framerate drops considerably (especially in NEI, as it drops from average mid 110s to mid 10s. in-world naga causes framerate drops but not as massively.)

### Your Proposal

Figure out what's going on and fix the fps problem.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sisyphussy** [comment]
Can you profile it with VisualVM or Spark client and send the results?

**Comment by BadsyEdgecat** [comment]
Issue also happens, in NEI, with Block and Chain Goblin,  and Snow Queen.

i dont know what those are, sorry. but it can be tested by someone who does fairly simply, by looking at naga scales in nei

**Comment by sisyphussy** [comment]
NEI issue should be fixed in 2.8.1

**Comment by jjlpstar123** [comment]
I am running 2.8.4 and appear to still be running into the NEI issue. When viewing the mob info for the naga my framerate drops significantly, which causes me to be unable to exit the inventory in any way and results in having to close the client entirely externally. I am using the prism launcher and running Java 21.

**Comment by spikeck2-mun** [comment]
I can confirm this is still an issue. The game runs perfectly fine but performance drops massively when the Naga is on screen or even displayed in the NEI interface.

GTNH version 2.8.4
Java 25.0.1 - amd64
Prism Launcher version 10.0.5

PS. While the Naga and the Snow Queen are displayed in the NEI mob preview window the frames drop to around 4fps. Allocating more RAM hasn't solved the issue. My Prism log spams this while the issue is occurring (The last number alternates between 26 and 27 if that makes any difference):

[14:43:24] [Client thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:320]: Negative index in crash report handler (0/26)
