### ISSUE TITLE
nanosuit boots of traveller is borked on 0% speed

### ISSUE THREAD

**Issue by EnderNon** [GTNewHorizons/GT-New-Horizons-Modpack#22283]
### Your Pack Version

2.8.1

### Your Server

private server multiplayer (forge)

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

At 0% speed set (default), I expect movement to be exactly the same as it happens in vanilla.

### The Reality

At 0% speed set, jumping causes your velocity to slow down horizontally. And while midair with jetpack, you are also slowed down significantly. Glider is same as vanilla.

### Your Proposal

fix whatever the hell causes you to be so slow in the air

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SST-03** [comment]
Can confirm in 2.7.3 and 2.8.0
I dont sure if this is a bug

**Comment by EnderNon** [comment]
> Can confirm in 2.7.3 and 2.8.0 I dont sure if this is a bug

why is it even like this??

**Comment by SST-03** [comment]
> why is it even like this??

I don't sure but this may be a bug. Also this cannot reproduce when you can creative-fly (for example gravity armor), so I think it's a jetpack problem. ~Maybe because [this](https://github.com/GTNewHorizons/Electro-Magic-Tools/blob/9a51e36a331138226fa9c20c29de24cce92d57b9/src/main/java/emt/item/armor/boots/ItemElectricBootsTraveller.java#L131)? (Needs to check)~

**Comment by SST-03** [comment]
Wait if jumping can also reproduce this problem, then I guess it's a feature from TC4 boots of traveller
[Link](https://github.com/GTNewHorizons/Electro-Magic-Tools/blob/9a51e36a331138226fa9c20c29de24cce92d57b9/src/main/java/emt/item/armor/boots/ItemElectricBootsTraveller.java#L171) OK so if speed == 0 you cannot move when jumping. But I dont sure if fixing this will affect other things,

**Comment by sisyphussy** [comment]
Should be fixed by https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/109

**Comment by SST-03** [comment]
> Should be fixed by [GTNewHorizons/Electro-Magic-Tools#109](https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/109)

No you still doesn't fixed this bug/feature. After your fix speed of nano boots of traveller will be 100% in default, but when you set the speed to 0% you still can't move.

**Comment by EnderNon** [comment]
it's still borked on 2.8.4

**Comment by SST-03** [comment]
It's fixed in 2.9.0, but not fixed in 2.8.x
If there is 2.8.5 I can sync the fix to 2.8.x



---Original---
From: "ender ***@***.***&gt;
Date: Thu, Dec 25, 2025 08:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GTNewHorizons/GT-New-Horizons-Modpack] nanosuit boots oftraveller is borked on 0% speed (Issue #22283)


EnderNon left a comment (GTNewHorizons/GT-New-Horizons-Modpack#22283)
 
it's still borked on 2.8.4

**Comment by EnderNon** [comment]
> It's fixed in 2.9.0, but not fixed in 2.8.x
> If there is 2.8.5 I can sync the fix to 2.8.x
> […](#)

thats crazy
