### ISSUE TITLE
NBT type 10 crash, all backups deleted

### ISSUE THREAD

**Issue by Wad67** [GTNewHorizons/GT-New-Horizons-Modpack#22365]
### Your Pack Version

2.8.0

### Your Server

private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Nether dimension slowly reached critical mass of mobs, despite not being chunk loaded. However the overworld portal was chunk loaded. I suspect that pigman spawns backtracked through the portal. 

After a week or two of inactivity I joined the server and entered the portal, where I died instantly from a mobcap worth of pigmen. 

Eventually I gave up and loaded a backup before going to bed. Which caused the server to go into a reboot loop overnight. 

Unable to connect to the server the next day, I noted the restart loop, in addition the backups folder is now empty.  Curiously these backups are not in any Trash folders either.  Crash occurs immediately after a number of onworldload functions:
[01:41:43] [Server thread/ERROR] [FML]: 44: ASM: gregtech.common.misc.GlobalEnergyWorldSavedData@5a6b6028 onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
[01:41:43] [Server thread/ERROR] [FML]: 45: ASM: gregtech.common.GTWorldgenerator$OregenPatternSavedData@35884a8 onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
[01:41:43] [Server thread/ERROR] [FML]: 46: ASM: gregtech.common.misc.GlobalMetricsCoverDatabase@50a258ad onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
[01:41:43] [Server thread/ERROR] [FML]: 47: ASM: gregtech.common.powergoggles.PowerGogglesWorldSavedData@3a276578 onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
[01:41:43] [Server thread/ERROR] [FML]: 48: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@34697a6f onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
[01:41:43] [Server thread/ERROR] [FML]: 49: ASM: gregtech.common.data.GTPowerfailTracker@6b62e445 onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
[01:41:43] [Server thread/ERROR]: Encountered an unexpected exception

Unclear if related, cause of backups folder empty unclear. World presumably corrupted. Server routinely crashes on repeated attempts.  Unclear how to recover progress given loss of backups and presumed world corruption.  Kindly let me know if there is some way to salvage this. 

### Crash Report

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 11/3/25, 1:41 AM
Description: Loading NBT data

java.io.EOFException
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
	at Launch//net.minecraft.nbt.NBTTagCompound.func_152447_a(NBTTagCompound.java:383)
	at Launch//net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:48)
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_152458_a(CompressedStreamTools.java:216)
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_74797_a(CompressedStreamTools.java:200)
	at Launch//net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:421)
	at Launch//net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_41_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at Launch//net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230)
	at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
	at Launch//net.minecraft.nbt.NBTTagCompound.func_152447_a(NBTTagCompound.java:383)
	at Launch//net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:48)

-- NBT Tag --
Details:
	Tag name: [UNNAMED TAG]
	Tag type: 10
Stacktrace:
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_152458_a(CompressedStreamTools.java:216)
	at Launch//net.minecraft.nbt.CompressedStreamTools.func_74797_a(CompressedStreamTools.java:200)
	at Launch//net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:421)
	at Launch//net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_41_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at Launch//net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230)
	at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 6.8.0-85-generic
	Java Version: 21.0.8, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 3714471584 bytes (3542 MB) / 6227755008 bytes (5939 MB) up to 6227755008 bytes (5939 MB)
	JVM Flags: 2 total; -Xms6G -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 287 mods loaded, 287 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	appliedenergistics2-core{rv3-beta-690-GTNH} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAA	CodeChickenCore{1.4.7} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	CropLoadCoreASM{0.0.2} [CroploadCore ASM Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{2.7.91-GTNH} [NotEnoughItems] (NotEnoughItems-2.7.91-GTNH.jar) 
	UCHIJAA	OpenComputers|Core{1.11.19-GTNH} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAA	MobiusCore{1.4.6-mapless} [MobiusCore] (minecraft.jar) 
	UCHIJAA	PlayerAPI{1.5.0} [Player API] (minecraft.jar) 
	UCHIJAA	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
	UCHIJAA	GTNHLib Core{0.6.40} [GTNHLib Core] (minecraft.jar) 
	UCHIJAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAA	OpenModsCore{0.10.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	unimixins{0.1.23} [UniMixins] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	unimixins-mixin{0.1.23} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	unimixins-compat{0.1.23} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	mixinextras{0.1.23} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.23.jar) 
	UCHIJAA	IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828a-experimental.jar) 
	UCHIJAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1a.jar) 
	UCHIJAA	adventurebackpack{1.3.11-GTNH} [Adventure Backpack] (adventurebackpack-1.3.11-GTNH.jar) 
	UCHIJAA	gtnhlib{0.6.40} [GTNH Lib] (gtnhlib-0.6.40.jar) 
	UCHIJAA	appliedenergistics2{rv3-beta-690-GTNH} [Applied Energistics 2] (appliedenergistics2-rv3-beta-690-GTNH.jar) 
	UCHIJAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAA	Baubles{2.1.15-GTNH} [Baubles] (BaublesExpanded-2.1.15-GTNH.jar) 
	UCHIJAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5a.jar) 
	UCHIJAA	Waila{1.8.14} [Waila] (Waila-1.8.14.jar) 
	UCHIJAA	thaumicenergistics{1.7.14-GTNH} [Thaumic Energistics] (thaumicenergistics-1.7.14-GTNH.jar) 
	UCHIJAA	ae2wct{1.12.7} [AE2 Wireless Crafting Terminal] (WirelessCraftingTerminal-1.12.7.jar) 
	UCHIJAA	ae2fc{1.4.115-gtnh} [AE2 Fluid Crafting] (ae2fc-1.4.115-gtnh.jar) 
	UCHIJAA	ae2noultimatepatterns{1.0.1} [AE2NoUltimatePattern] (ae2noultimatepatterns-1.0.1.jar) 
	UCHIJAA	bdlib{1.11.0-GTNH} [BD lib] (bdlib-1.11.0-GTNH.jar) 
	UCHIJAA	ae2stuff{0.9.8-GTNH} [AE2 Stuff] (ae2stuff-0.9.8-GTNH.jar) 
	UCHIJAA	AFSU{1.3.1-GTNH} [AFSU Mod] (AFSU-1.3.1-GTNH.jar) 
	UCHIJAA	akashictome{1.2.6} [Akashic Tome] (akashictome-1.2.6.jar) 
	UCHIJAA	alchgrate{1.3.1-GTNH} [Alchemical Grate] (alchgrate-1.3.1-GTNH.jar) 
	UCHIJAA	amazingtrophies{1.3.8} [Amazing Trophies] (amazingtrophies-1.3.8.jar) 
	UCHIJAA	BuildCraft|Core{7.1.44} [BuildCraft] (buildcraft-7.1.44.jar) 
	UCHIJAA	BuildCraft|Energy{7.1.44} [BC Energy] (buildcraft-7.1.44.jar) 
	UCHIJAA	Mantle{0.5.1} [Mantle] (Mantle-0.5.1.jar) 
	UCHIJAA	battlegear2{1.5.8-backhand} [Mine & Blade Battlegear 2] (battlegear2-1.5.8-backhand.jar) 
	UCHIJAA	ForgeMultipart{1.6.8} [Forge Multipart] (ForgeMultipart-1.6.8.jar) 
	UCHIJAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAA	TConstruct{1.13.54-GTNH} [Tinkers' Construct] (TConstruct-1.13.54-GTNH.jar) 
	UCHIJAA	GalacticraftCore{3.3.12-GTNH} [Galacticraft Core] (Galacticraft-3.3.12-GTNH.jar) 
	UCHIJAA	GalacticraftMars{3.3.12-GTNH} [Galacticraft Planets] (Galacticraft-3.3.12-GTNH.jar) 
	UCHIJAA	backhand{1.7.6} [Backhand] (backhand-1.7.6.jar) 
	UCHIJAA	endercore{0.4.8} [EnderCore] (endercore-0.4.8.jar) 
	UCHIJAA	Natura{2.8.9} [Natura] (Natura-2.8.9.jar) 
	UCHIJAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJAA	HardcoreEnderExpansion{1.12.13-GTNH} [Hardcore Ender Expansion] (HardcoreEnderExpansion-1.12.13-GTNH.jar) 
	UCHIJAA	Forestry{4.10.17} [Forestry] (Forestry-4.10.17.jar) 
	UCHIJAA	BuildCraft|Builders{7.1.44} [BC Builders] (buildcraft-7.1.44.jar) 
	UCHIJAA	BuildCraft|Factory{7.1.44} [BC Factory] (buildcraft-7.1.44.jar) 
	UCHIJAA	Railcraft{9.16.33} [Railcraft] (Railcraft-9.16.33.jar) 
	UCHIJAA	EnderIO{2.9.26} [Ender IO] (EnderIO-2.9.26.jar) 
	UCHIJAA	supersolarpanel{1.1.4} [Super Solar Panel] (supersolarpanel-1.1.4.jar) 
	UCHIJAA	YAMCore{0.7.1} [YAMCore] (YAMCore-0.7.1.jar) 
	UCHIJAA	dreamcraft{2.7.260} [GT: New Horizons] (GTNewHorizonsCoreMod-2.7.260.jar) 
	UCHIJAA	IronChest{6.1.6} [Iron Chests] (IronChest-6.1.6.jar) 
	UCHIJAA	GalacticraftAmunRa{0.8.2} [Amun-Ra] (AmunRa-GC-0.8.2.jar) 
	UCHIJAA	angermod{0.9.0} [AngerMod. Makes your Mobs angry!] (AngerMod-0.9.0.jar) 
	UCHIJAA	AppleCore{3.3.7} [AppleCore] (AppleCore-3.3.7.jar) 
	UCHIJAA	archaicfix{0.7.7} [ArchaicFix] (archaicfix-0.7.7.jar) 
	UCHIJAA	ArchitectureCraft{1.11.5} [ArchitectureCraft] (ArchitectureCraft-1.11.5.jar) 
	UCHIJAA	asielib{0.7.0} [AsieLib] (AsieLib-0.7.0.jar) 
	UCHIJAA	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHIJAA	AWWayofTime{1.7.51} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.51.jar) 
	UCHIJAA	Botania{1.12.26-GTNH} [Botania] (Botania-1.12.26-GTNH.jar) 
	UCHIJAA	Avaritia{1.75} [Avaritia] (Avaritia-1.75.jar) 
	UCHIJAA	wanionlib{1.10.0} [WanionLib] (WanionLib-1.10.0.jar) 
	UCHIJAA	avaritiaddons{1.9.1-GTNH} [Avaritiaddons] (Avaritiaddons-1.9.1-GTNH.jar) 
	UCHIJAA	Backpack{2.5.9-GTNH} [Backpack Edited for ModdedNetwork] (backpack-2.5.9-GTNH.jar) 
	UCHIJAA	Baubles|Expanded{2.1.15-GTNH} [Baubles Expanded] (BaublesExpanded-2.1.15-GTNH.jar) 
	UCHIJAA	betterbuilderswands{0.13.3-GTNH} [BetterBuildersWands] (BetterBuildersWands-0.13.3-GTNH.jar) 
	UCHIJAA	forgelin{2.0.3-GTNH} [Forgelin] (forgelin-2.0.3-GTNH.jar) 
	UCHIJAA	betterp2p{1.3.2} [BetterP2P] (betterp2p-1.3.2.jar) 
	UCHIJAA	betterquesting{3.7.14-GTNH} [BetterQuesting] (BetterQuesting-3.7.14-GTNH.jar) 
	UCHIJAA	bq_standard{3.7.14-GTNH} [Standard Expansion] (BetterQuesting-3.7.14-GTNH.jar) 
	UCHIJAA	cb4bq{3.7.14-GTNH} [Command Blocks for Better Questing] (BetterQuesting-3.7.14-GTNH.jar) 
	UCHIJAA	questbook{3.7.14-GTNH} [BetterQuesting] (BetterQuesting-3.7.14-GTNH.jar) 
	UCHIJAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJAA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJAA	BinnieCore{2.5.22} [Binnie Core] (binnie-mods-2.5.22.jar) 
	UCHIJAA	ExtraBees{2.5.22} [Extra Bees] (binnie-mods-2.5.22.jar) 
	UCHIJAA	Genetics{2.5.22} [Genetics] (binnie-mods-2.5.22.jar) 
	UCHIJAA	ExtraTrees{2.5.22} [Extra Trees] (binnie-mods-2.5.22.jar) 
	UCHIJAA	Botany{2.5.22} [Botany] (binnie-mods-2.5.22.jar) 
	UCHIJAA	blocklimiter{0.7.0} [BlockLimiter. Restrict your Blocks] (BlockLimiter-0.7.0.jar) 
	UCHIJAA	structurelib{1.4.23} [StructureLib] (structurelib-1.4.23.jar) 
	UCHIJAA	blockrenderer6343{1.3.16} [BlockRenderer6343] (blockrenderer6343-1.3.16.jar) 
	UCHIJAA	ThaumicTinkerer{2.11.26} [Thaumic Tinkerer] (ThaumicTinkerer-2.11.26.jar) 
	UCHIJAA	ForbiddenMagic{0.8.3-GTNH} [Forbidden Magic] (Forbidden.Magic-0.8.3-GTNH.jar) 
	UCHIJAA	BloodArsenal{1.4.10} [Blood Arsenal] (BloodArsenal-1.4.10.jar) 
	UCHIJAA	hodgepodge{2.6.108} [Hodgepodge] (hodgepodge-2.6.108.jar) 
	UCHIJAA	modularui2{2.2.18-1.7.10} [Modular UI 2] (modularui2-2.2.18-1.7.10.jar) 
	UCHIJAA	craftingtweaks{1.2.65-GTNH} [Gregory Tweaks For Crafting] (bogosorter-1.2.65-GTNH.jar) 
	UCHIJAA	bogosorter{1.2.65-GTNH} [Inventory Bogo Sorter] (bogosorter-1.2.65-GTNH.jar) 
	UCHIJAA	MouseTweaks{1.2.65-GTNH} [Mouse Tweaks Unofficial] (bogosorter-1.2.65-GTNH.jar) 
	UCHIJAA	TwilightForest{2.7.13} [The Twilight Forest] (TwilightForest-2.7.13.jar) 
	UCHIJAA	chisel{2.16.13-GTNH} [Chisel] (chisel-2.16.13-GTNH.jar) 
	UCHIJAA	BuildCraft|Silicon{7.1.44} [BC Silicon] (buildcraft-7.1.44.jar) 
	UCHIJAA	BuildCraft|Transport{7.1.44} [BC Transport] (buildcraft-7.1.44.jar) 
	UCHIJAA	MagicBees{2.9.4-GTNH} [Magic Bees] (magicbees-2.9.4-GTNH.jar) 
	UCHIJAA	gendustry{1.9.4-GTNH} [Gendustry] (gendustry-1.9.4-GTNH.jar) 
	UCHIJAA	ggfab{5.09.51.470} [GigaGramFab] (gregtech-5.09.51.470.jar) 
	UCHIJAA	harvestcraft{1.3.2-GTNH} [Pam's HarvestCraft] (harvestcraft-1.3.2-GTNH.jar) 
	UCHIJAA	modularui{1.2.20} [ModularUI] (modularui-1.2.20.jar) 
	UCHIJAA	Translocator{1.3.1} [Translocator] (Translocator-1.3.1.jar) 
	UCHIJAA	gregtech{MC1710} [GregTech] (gregtech-5.09.51.470.jar) 
	UCHIJAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAA	botanichorizons{1.11.24-GTNH} [botanichorizons] (BotanicHorizons-1.11.24-GTNH.jar) 
	UCHIJAA	BrandonsCore{1.2.0-GTNH} [Brandon's Core] (BrandonsCore-1.2.0-GTNH.jar) 
	UCHIJAA	bugtorch{1.2.14} [BugTorch] (bugtorch-1.2.14.jar) 
	UCHIJAA	BuildCraft|Robotics{7.1.44} [BC Robotics] (buildcraft-7.1.44.jar) 
	UCHIJAA	BuildCraft|Compat{7.1.18} [BuildCraft Compat] (buildcraft-compat-7.1.18.jar) 
	UCHIJAA	OilTweak{1.1.1} [BuildCraft Oil Tweak] (BuildCraftOilTweak-1.1.1.jar) 
	UCHIJAA	CarpentersBlocks{3.7.0-GTNH} [Carpenter's Blocks] (CarpentersBlocks-3.7.0-GTNH.jar) 
	UCHIJAA	catwalks{2.0.4} [Catwalks Mod] (catwalks-2.4.0-GTNH.jar) 
	UCHIJAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.2.jar) 
	UCHIJAA	chiseltones{1.2.0-GTNH} [Chisel Tones] (chiseltones-1.2.0-GTNH.jar) 
	UCHIJAA	compactkineticgenerators{1.7.10-1.0} [Compact Kinetic Wind and Water Generators] (CompactKineticGenerators-1.7.10-1.0.jar) 
	UCHIJAA	EnderStorage{1.7.7} [EnderStorage] (EnderStorage-1.7.7.jar) 
	UCHIJAA	MrTJPCoreMod{1.3.4} [MrTJPCore] (MrTJPCore-1.3.4.jar) 
	UCHIJAA	ProjRed|Core{4.11.13-GTNH} [ProjectRed Core] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	ProjRed|Transmission{4.11.13-GTNH} [ProjectRed Transmission] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	OpenComputers{1.11.19-GTNH} [OpenComputers] (OpenComputers-1.11.19-GTNH.jar) 
	UCHIJAA	computronics{1.9.3-GTNH} [Computronics] (Computronics-1.9.3-GTNH.jar) 
	UCHIJAA	cookingforblockheads{1.4.4-GTNH} [Cooking For Blockheads] (CookingForBlockheads-1.4.4-GTNH.jar) 
	UCHIJAA	coretweaks{0.3.3.6-GTNH} [CoreTweaks] (coretweaks-0.3.3.6-GTNH.jar) 
	UCHIJAA	MineTweaker3{3.4.2} [MineTweaker 3] (CraftTweaker-3.4.2.jar) 
	UCHIJAA	DummyCore{1.20.0} [DummyCore] (DummyCore-1.20.0.jar) 
	UCHIJAA	thaumicbases{1.8.13} [Thaumic Bases] (Thaumic-Based-1.8.13.jar) 
	UCHIJAA	croploadcore{0.2.0} [CropLoadCore] (CropLoadCore-0.2.0.jar) 
	UCHIJAA	berriespp{1.8.11} [Crops++] (CropsPP-1.8.11.jar) 
	UCHIJAA	darkerer{1.0.6} [Darkerer] (darkerer-1.0.6.jar) 
	UCHIJAA	DraconicEvolution{1.4.27-GTNH} [Draconic Evolution] (Draconic-Evolution-1.4.27-GTNH.jar) 
	UCHIJAA	EMT{1.6.17} [Electro-Magic Tools] (EMT-1.6.17.jar) 
	UCHIJAA	EnderZoo{1.3.3} [Ender Zoo] (EnderZoo-1.3.3.jar) 
	UCHIJAA	enhancedlootbags{1.2.8} [Enhanced LootBags] (EnhancedLootBags-1.2.8.jar) 
	UCHIJAA	universalsingularities{8.10.0} [UniversalSingularities] (Universal-Singularities-8.10.0.jar) 
	UCHIJAA	eternalsingularity{1.2.1} [Eternal Singularity] (eternalsingularity-1.2.1.jar) 
	UCHIJAA	etfuturum{2.6.2.25-GTNH} [Et Futurum Requiem] (etfuturum-2.6.2.25-GTNH.jar) 
	UCHIJAA	findit{1.4.0} [FindIt] (findit-1.4.0.jar) 
	UCHIJAA	FloodLights{1.5.4} [Flood Lights] (FloodLights-1.5.4.jar) 
	UCHIJAA	McMultipart{1.6.8} [Minecraft Multipart Plugin] (ForgeMultipart-1.6.8.jar) 
	UCHIJAA	ForgeMicroblock{1.6.8} [Forge Microblocks] (ForgeMultipart-1.6.8.jar) 
	UCHIJAA	ForgeRelocation{0.3.4} [ForgeRelocation] (ForgeRelocation-0.3.4.jar) 
	UCHIJAA	MCFrames{0.3.4} [MCFrames] (ForgeRelocation-0.3.4.jar) 
	UCHIJAA	RelocationFMP{0.2.0} [RelocationFMP] (ForgeRelocationFMP-0.2.0.jar) 
	UCHIJAA	gadomancy{1.4.7} [Gadomancy] (gadomancy-1.4.7.jar) 
	UCHIJAA	GalaxySpace{1.1.121-GTNH} [GalaxySpace] (GalaxySpace-1.1.121-GTNH.jar) 
	UCHIJAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAA	gravisuiteneo{1.3.6} [Gravitation Suite Neo] (gravisuiteneo-1.3.6.jar) 
	UCHIJAA	gtneioreplugin{5.09.51.470} [GT NEI Ore Plugin GT:NH Mod] (gregtech-5.09.51.470.jar) 
	UCHIJAA	galacticgreg{5.09.51.470} [Galactic Greg] (gregtech-5.09.51.470.jar) 
	UCHIJAA	tectech{5.09.51.470} [TecTech - Tec Technology!] (gregtech-5.09.51.470.jar) 
	UCHIJAA	ProjRed|Illumination{4.11.13-GTNH} [ProjectRed Illumination] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	RandomThings{2.6.6} [RandomThings] (RandomThings-2.6.6.jar) 
	UCHIJAA	bartworks{5.09.51.470} [BartWorks] (gregtech-5.09.51.470.jar) 
	UCHIJAA	GoodGenerator{5.09.51.470} [Good Generator] (gregtech-5.09.51.470.jar) 
	UCHIJAA	gtnhlanth{5.09.51.470} [GTNH: Lanthanides] (gregtech-5.09.51.470.jar) 
	UCHIJAA	bartworkscrossmodtgregworkscontainer{5.09.51.470} [BartWorks Mod Additions - TGregworks Container] (gregtech-5.09.51.470.jar) 
	UCHIJAA	gregtech_nh{5.09.51.470} [GregTech GTNH] (gregtech-5.09.51.470.jar) 
	UCHIJAA	IC2NuclearControl{2.6.20} [Nuclear Control 2] (IC2NuclearControl-2.6.20.jar) 
	UCHIJAA	OpenMods{0.10.10} [OpenMods] (OpenModsLibs-0.10.10.jar) 
	UCHIJAA	OpenBlocks{1.11.7-GTNH} [OpenBlocks] (OpenBlocks-1.11.7-GTNH.jar) 
	UCHIJAA	StevesCarts{2.3.12} [Steve's Carts 2] (StevesCarts-2.3.12.jar) 
	UCHIJAA	TGregworks{1.7.10-GTNH-1.0.28} [Tinkers' Gregworks] (TGregworks-1.7.10-GTNH-1.0.28.jar) 
	UCHIJAA	miscutils{5.09.51.470} [GT++] (gregtech-5.09.51.470.jar) 
	UCHIJAA	bartworkscrossmod{5.09.51.470} [BartWorks Mod Additions] (gregtech-5.09.51.470.jar) 
	UCHIJAA	InfernalMobs{1.10.3-GTNH} [Infernal Mobs] (InfernalMobs-1.10.3-GTNH.jar) 
	UCHIJAA	mobsinfo{0.5.4-GTNH} [MobsInfo] (mobsinfo-0.5.4-GTNH.jar) 
	UCHIJAA	kubatech{5.09.51.470} [KubaTech] (gregtech-5.09.51.470.jar) 
	UCHIJAA	detravscannermod{5.09.51.470} [GT Scanner Mod] (gregtech-5.09.51.470.jar) 
	UCHIJAA	kekztech{5.09.51.470} [KekzTech] (gregtech-5.09.51.470.jar) 
	UCHIJAA	openmodularturrets{2.4.3} [Open Modular Turrets] (OpenModularTurrets-2.4.3.jar) 
	UCHIJAA	gtnhintergalactic{5.09.51.470} [GTNH-Intergalactic] (gregtech-5.09.51.470.jar) 
	UCHIJAA	ToxicEverglades{5.09.51.470} [GregTech ToxicEverglades] (gregtech-5.09.51.470.jar) 
	UCHIJAA	TaintedMagic{r7.6} [Tainted Magic] (Tainted-Magic-7.6.26-GTNH.jar) 
	UCHIJAA	ThaumicExploration{1.4.7-GTNH} [Thaumic Exploration] (Thaumic-Exploration-1.4.7-GTNH.jar) 
	UCHIJAA	gtnhtcwands{1.4.6} [GTNH-TC-Wands] (GTNH-TC-Wands-1.4.6.jar) 
	UCHIJAA	GTTweaker{2.3.1} [GTTweaker] (GTTweaker-2.3.1.jar) 
	UCHIJAA	HelpFixer{1.3.0} [HelpFixer] (HelpFixer-1.3.0.jar) 
	UCHIJAA	holoinventory{2.5.5-GTNH} [Holo Inventory] (holoinventory-2.5.5-GTNH.jar) 
	UCHIJAA	hydroenergy{1.4.9} [HydroEnergy] (hydroenergy-1.4.9.jar) 
	UCHIJAA	ifu{1.11.2} [I Will Find You] (ifu-1.11.2.jar) 
	UCHIJAA	LunatriusCore{1.2.1-GTNH} [LunatriusCore] (LunatriusCore-1.2.1-GTNH.jar) 
	UCHIJAA	InGameInfoXML{2.8.29} [InGame Info XML] (InGameInfoXML-2.8.29.jar) 
	UCHIJAA	ironchestminecarts{1.2.0} [Iron Chest Minecarts] (IronChestMinecarts-1.2.0.jar) 
	UCHIJAA	irontank{1.4.2} [Iron Tanks] (irontanks-1.4.2.jar) 
	UCHIJAA	irontankminecarts{1.0.12} [Iron Tank Minecarts] (irontankminecarts-1.0.12.jar) 
	UCHIJAA	JABBA{1.5.10} [JABBA] (JABBA-1.5.10.jar) 
	UCHIJAA	JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.5_MC1.7.10.jar) 
	UCHIJAA	littletiles{1.5.14-GTNH} [LittleTiles] (littletiles-1.5.14-GTNH.jar) 
	UCHIJAA	creativecore{1.5.14-GTNH} [CreativeCore] (littletiles-1.5.14-GTNH.jar) 
	UCHIJAA	LogisticsPipes{1.4.24-GTNH} [Logistics Pipes] (logisticspipes-1.4.24-GTNH.jar) 
	UCHIJAA	lootgames{2.2.0} [LootGames] (lootgames-2.2.0.jar) 
	UCHIJAA	lwjgl3ify{2.1.15} [lwjgl3ify] (lwjgl3ify-2.1.15.jar) 
	UCHIJAA	malisiscore{1.18.2-GTNH} [Malisis Core] (malisisdoors-1.18.2-GTNH.jar) 
	UCHIJAA	malisisdoors{1.18.2-GTNH} [Malisis' Doors] (malisisdoors-1.18.2-GTNH.jar) 
	UCHIJAA	matter-manipulator{0.0.49-GTNH} [Matter Manipulator] (matter-manipulator-0.0.49-GTNH.jar) 
	UCHIJAA	modernmarkings{0.3.12-1.7.10} [ModernMarkings] (modernmarkings-0.3.12-1.7.10.jar) 
	UCHIJAA	modtweaker2{0.12.0} [Mod Tweaker 2] (ModTweaker2-0.12.0.jar) 
	UCHIJAA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCHIJAA	naturescompass{1.5.0-GTNH} [Nature's Compass] (naturescompass-1.5.0-GTNH.jar) 
	UCHIJAA	navigator{1.0.17} [Navigator] (navigator-1.0.17.jar) 
	UCHIJAA	NEIAddons{1.17.0} [NEI Addons] (NEIAddons-1.17.0.jar) 
	UCHIJAA	NEIAddons|Botany{1.17.0} [NEI Addons: Botany] (NEIAddons-1.17.0.jar) 
	UCHIJAA	NEIAddons|Developer{1.17.0} [NEI Addons: Developer Tools] (NEIAddons-1.17.0.jar) 
	UCHIJAA	NEIAddons|ExNihilo{1.17.0} [NEI Addons: Ex Nihilo] (NEIAddons-1.17.0.jar) 
	UCHIJAA	NEIAddons|CraftingTables{1.17.0} [NEI Addons: Crafting Tables] (NEIAddons-1.17.0.jar) 
	UCHIJAA	NEIAddons|Forestry{1.17.0} [NEI Addons: Forestry] (NEIAddons-1.17.0.jar) 
	UCHIJAA	NEIAddons|AppEng{1.17.0} [NEI Addons: Applied Energistics 2] (NEIAddons-1.17.0.jar) 
	UCHIJAA	neicustomdiagram{1.7.5} [NEI Custom Diagram] (NEICustomDiagram-1.7.5.jar) 
	UCHIJAA	neiintegration{1.5.0} [NEIIntegration] (NEIIntegration-1.5.0.jar) 
	UCHIJAA	netherportalfix{1.4.0} [Nether Portal Fix] (netherportalfix-1.4.0.jar) 
	UCHIJAA	NodalMechanics{1.3.1-GTNH} [NodalMechanics] (NodalMechanics-1.3.1-GTNH.jar) 
	UCHIJAA	neenergistics{1.7.14} [NotEnoughEnergistics] (NotEnoughEnergistics-1.7.14.jar) 
	UCHIJAA	neid{2.1.10} [NotEnoughIDs] (notenoughIDs-2.1.10.jar) 
	UCHIJAA	nutrition{0.1.3} [Nutrition] (nutrition-0.1.3.jar) 
	UCHIJAA	openglasses{1.6.1-GTNH} [OC Glasses] (OpenGlasses-1.6.1-GTNH.jar) 
	UCHIJAA	openprinter{0.3.0-GTNH} [OpenPrinter] (openprinter-0.3.0-GTNH.jar) 
	UCHIJAA	opensecurity{1.2.0-GTNH} [OpenSecurity] (opensecurity-1.2.0-GTNH.jar) 
	UCHIJAA	Opis{1.4.6-mapless} [Opis] (Opis-1.4.6-mapless.jar) 
	UCHIJAA	harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's Harvest the Nether 1.7.10a.jar) 
	UCHIJAA	personalspace{1.0.33} [PersonalSpace] (personalspace-1.0.33.jar) 
	UCHIJAA	postea{1.1.3} [Postea] (postea-1.1.3.jar) 
	UCHIJAA	ProjectBlue{1.2.1-GTNH} [Project Blue] (ProjectBlue-1.2.1-GTNH.jar) 
	UCHIJAA	ProjRed|Exploration{4.11.13-GTNH} [ProjectRed Exploration] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	ProjRed|Transportation{4.11.13-GTNH} [ProjectRed Transportation] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	ProjRed|Compatibility{4.11.13-GTNH} [ProjectRed Compatibility] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	ProjRed|Integration{4.11.13-GTNH} [ProjectRed Integration] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	ProjRed|Fabrication{4.11.13-GTNH} [ProjectRed Fabrication] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	ProjRed|Expansion{4.11.13-GTNH} [ProjectRed Expansion] (ProjRed-4.11.13-GTNH.jar) 
	UCHIJAA	RIO{2.7.6} [RemoteIO] (RemoteIO-2.7.6.jar) 
	UCHIJAA	Roguelike{1.6.6-GTNH} [Roguelike Dungeons] (roguelike-1.6.6-GTNH.jar) 
	UCHIJAA	RWG{alpha-1.5.0} [Realistic World Gen Alpha] (RWG-alpha-1.5.0.jar) 
	UCHIJAA	tc4tweak{1.5.39} [TC4 Tweak] (Thaumcraft4Tweaks-1.5.39.jar) 
	UCHIJAA	salisarcana{1.1.33-GTNH} [Salis Arcana] (salisarcana-1.1.33-GTNH.jar) 
	UCHIJAA	serverutilities{2.1.61} [ServerUtilities] (ServerUtilities-2.1.61.jar) 
	UCHIJAA	SGCraft{1.4.5-GTNH} [SG Craft] (SGCraft-1.4.5-GTNH.jar) 
	UCHIJAA	sharewhereiam{2.1.4} [Share Where I am] (sharewhereiam-2.1.4.jar) 
	UCHIJAA	sleepingbag{0.3.0} [Sleeping Bag] (sleepingbag-0.3.0.jar) 
	UCHIJAA	SpecialMobs{3.7.0} [Special Mobs] (SpecialMobs-3.7.0.jar) 
	UCHIJAA	SpiceOfLife{2.2.3-carrot} [The Spice of Life - Carrot Edition] (SpiceOfLife-2.2.3-carrot.jar) 
	UCHIJAA	StevesFactoryManager{1.3.4-GTNH} [Steve's Factory Manager] (StevesFactoryManager-1.3.4-GTNH.jar) 
	UCHIJAA	StevesAddons{0.14.2} [Steve's Addons] (StevesAddons-0.14.2.jar) 
	UCHIJAA	StorageDrawers{2.1.8-GTNH} [Storage Drawers] (StorageDrawers-2.1.8-GTNH.jar) 
	UCHIJAA	StorageDrawersBop{2.1.8-GTNH} [Storage Drawers: Biomes O' Plenty Pack] (StorageDrawers-2.1.8-GTNH.jar) 
	UCHIJAA	StorageDrawersMisc{2.1.8-GTNH} [Storage Drawers: Misc Pack] (StorageDrawers-2.1.8-GTNH.jar) 
	UCHIJAA	StorageDrawersForestry{2.1.8-GTNH} [Storage Drawers: Forestry Pack] (StorageDrawers-2.1.8-GTNH.jar) 
	UCHIJAA	StorageDrawersNatura{2.1.8-GTNH} [Storage Drawers: Natura Pack] (StorageDrawers-2.1.8-GTNH.jar) 
	UCHIJAA	StorageDrawersErebus{2.1.8-GTNH} [Storage Drawers: Erebus Pack Pack] (StorageDrawers-2.1.8-GTNH.jar) 
	UCHIJAA	structurecompat{0.7.4} [StructureCompat] (structurecompat-0.7.4.jar) 
	UCHIJAA	SuperTic{1.5.0} [SuperTic] (SuperTic-1.5.0.jar) 
	UCHIJAA	thaumcraftneiplugin{1.7.10-1.7a} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAA	tcneiadditions{1.5.4} [Thaumcraft NEI Additions] (tcneiadditions-1.5.4.jar) 
	UCHIJAA	ThaumcraftMobAspects{1.2.1-GTNH} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.2.1-GTNH.jar) 
	UCHIJAA	ThaumcraftResearchTweaks{1.3.0} [Thaumcraft Research Tweaks] (ThaumcraftResearchTweaks-1.3.0.jar) 
	UCHIJAA	ThaumicMachina{0.2.1} [Thaumic Machina] (Thaumic Machina-1.7.10-0.2.1.jar) 
	UCHIJAA	thaumicboots{1.4.14} [Thaumic Boots] (thaumicboots-1.4.14.jar) 
	UCHIJAA	ThaumicHorizons{1.7.8} [ThaumicHorizons] (ThaumicHorizons-1.7.8.jar) 
	UCHIJAA	thaumicinsurgence{0.4.0} [Thaumic Insurgence] (thaumicinsurgence-0.4.0.jar) 
	UCHIJAA	tinkersdefense{1.3.2} [Tinkers Defense] (tinkersdefense-1.3.2.jar) 
	UCHIJAA	TMechworks{0.4.1} [Tinkers Mechworks] (TMechworks-0.4.1.jar) 
	UCHIJAA	TML{4.3.0-GTNH} [TooMuchLoot] (TooMuchLoot-4.3.0-GTNH.jar) 
	UCHIJAA	visualprospecting{1.4.8} [VisualProspecting] (visualprospecting-1.4.8.jar) 
	UCHIJAA	WailaHarvestability{1.3.4-GTNH} [Waila Harvestability] (WailaHarvestability-1.3.4-GTNH.jar) 
	UCHIJAA	wailaplugins{0.6.0} [WAILA Plugins] (WAILAPlugins-0.6.0.jar) 
	UCHIJAA	WarpTheory{1.5.0-GTNH} [WarpTheory] (WarpTheory-1.5.0-GTNH.jar) 
	UCHIJAA	wawla{1.3.1-GTNH} [What Are We Looking At] (Wawla-1.3.1-GTNH.jar) 
	UCHIJAA	WitcheryExtras{1.3.6} [Witchery++] (WitcheryExtras-1.3.6.jar) 
	UCHIJAA	WitchingGadgets{1.7.24-GTNH} [Witching Gadgets] (WitchingGadgets-1.7.24-GTNH.jar) 
	UCHIJAA	WR-CBE|Core{1.7.1} [WR-CBE Core] (WR-CBE-1.7.1.jar) 
	UCHIJAA	WR-CBE|Logic{1.7.1} [WR-CBE Logic] (WR-CBE-1.7.1.jar) 
	UCHIJAA	WR-CBE|Addons{1.7.1} [WR-CBE Addons] (WR-CBE-1.7.1.jar) 
	UCHIJAA	HungerOverhaul{1.7.10-1.0.0.jenkins104} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jenkins104.jar) 
	UCHIJAA	IguanaTweaksTConstruct{2.6.6} [Iguana Tinker Tweaks] (IguanaTweaksTConstruct-2.6.6.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	AE2 Version: rv3-beta-690-GTNH for Forge 10.13.4.1614
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: Environment healthy.
	CPU Threads: 1
	TC4Tweak signing signature: 473C3A397676978FF4877ABA2D57860DDA20E2FC, Built by: glease
	List of loaded APIs: 
		* ae2wct|API (1.7.10-rv3-1.8.6b) from WirelessCraftingTerminal-1.12.7.jar
		* Amazing Trophies API (1.3.8) from amazingtrophies-1.3.8.jar
		* AppleCoreAPI (3.3.7) from AppleCore-3.3.7.jar
		* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-690-GTNH.jar
		* asielibAPI (1.1) from AsieLib-0.7.0.jar
		* asielibAPI|chat (1.0) from AsieLib-0.7.0.jar
		* asielibAPI|tile (1.0) from AsieLib-0.7.0.jar
		* asielibAPI|tool (1.1) from AsieLib-0.7.0.jar
		* BattlePlayer (0.1) from battlegear2-1.5.8-backhand.jar
		* Baubles|API (2.1.2) from BaublesExpanded-2.1.15-GTNH.jar
		* BetterQuesting|API (3.2) from BetterQuesting-3.7.14-GTNH.jar
		* BetterQuesting|API2 (3.1) from BetterQuesting-3.7.14-GTNH.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
		* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.51.jar
		* BotaniaAPI (76) from Botania-1.12.26-GTNH.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.44.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.44.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.44.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.44.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.44.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.44.jar
		* BuildCraftAPI|recipes (3.1) from buildcraft-7.1.44.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.44.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.44.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.1.44.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.44.jar
		* CarpentersBlocks|API (3.3.7) from CarpentersBlocks-3.7.0-GTNH.jar
		* ChiselAPI (0.1.1) from chisel-2.16.13-GTNH.jar
		* ChiselAPI|Carving (0.1.1) from chisel-2.16.13-GTNH.jar
		* ChiselAPI|Rendering (0.1.1) from chisel-2.16.13-GTNH.jar
		* CoFHAPI (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|energy (1.7.10R1.3.1) from FloodLights-1.5.4.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|inventory (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|item (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|transport (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|container (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|slot (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render|particle (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|helpers (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|position (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|world|feature (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* computronicsAPI (1.3) from Computronics-1.9.3-GTNH.jar
		* computronicsAPI|audio (1.0) from Computronics-1.9.3-GTNH.jar
		* computronicsAPI|chat (1.3) from Computronics-1.9.3-GTNH.jar
		* computronicsAPI|multiperipheral (1.1) from Computronics-1.9.3-GTNH.jar
		* computronicsAPI|tape (1.0) from Computronics-1.9.3-GTNH.jar
		* CraftingTweaks|API (4.1) from bogosorter-1.2.65-GTNH.jar
		* DraconicEvolution|API (1.2) from Draconic-Evolution-1.4.27-GTNH.jar
		* DualWield (0.1) from battlegear2-1.5.8-backhand.jar
		* EnderIOAPI (0.0.2) from EnderIO-2.9.26.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-2.9.26.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-2.9.26.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-2.9.26.jar
		* ForestryAPI|apiculture (5.0.0) from Forestry-4.10.17.jar
		* ForestryAPI|arboriculture (4.2.1) from Forestry-4.10.17.jar
		* ForestryAPI|circuits (3.1.0) from Forestry-4.10.17.jar
		* ForestryAPI|core (5.0.0) from Forestry-4.10.17.jar
		* ForestryAPI|farming (2.1.0) from Forestry-4.10.17.jar
		* ForestryAPI|food (1.1.0) from Forestry-4.10.17.jar
		* ForestryAPI|fuels (2.0.1) from Forestry-4.10.17.jar
		* ForestryAPI|genetics (4.7.1) from Forestry-4.10.17.jar
		* ForestryAPI|hives (4.1.0) from Forestry-4.10.17.jar
		* ForestryAPI|lepidopterology (1.3.0) from Forestry-4.10.17.jar
		* ForestryAPI|mail (3.0.0) from Forestry-4.10.17.jar
		* ForestryAPI|multiblock (3.0.0) from Forestry-4.10.17.jar
		* ForestryAPI|recipes (5.4.0) from Forestry-4.10.17.jar
		* ForestryAPI|storage (3.0.0) from Forestry-4.10.17.jar
		* ForestryAPI|world (2.1.0) from Forestry-4.10.17.jar
		* ForgeRelocation|API (0.3.4) from ForgeRelocation-0.3.4.jar
		* Galacticraft API (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Blocks (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Client Events (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Core Prefabs (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Entities (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Entity Prefabs (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Galaxies (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Items (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Oxygen Events (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Power (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Prefabs (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Recipes (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Tile Entities (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Transmission (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Transmission|Grids (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Transmission|Tile Entities (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|Vectors (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|World (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|World Generation Events (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* Galacticraft API|World Generation Prefabs (3.3.12-GTNH) from Galacticraft-3.3.12-GTNH.jar
		* gendustryAPI (2.3.0) from gendustry-1.9.4-GTNH.jar
		* Heraldry (alpha) from battlegear2-1.5.8-backhand.jar
		* IC2API (1.0) from industrialcraft-2-2.2.828a-experimental.jar
		* MouseTweaks|API (1.0) from bogosorter-1.2.65-GTNH.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.6.20.jar
		* OilTweakAPI (1.1.1) from BuildCraftOilTweak-1.1.1.jar
		* OilTweakAPI|blacklist (1.1.1) from BuildCraftOilTweak-1.1.1.jar
		* OpenBlocks|API (1.1) from OpenBlocks-1.11.7-GTNH.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-1.11.19-GTNH.jar
		* ProjectRed API (4.11.13-GTNH) from ProjRed-4.11.13-GTNH.jar
		* Quiver (0.2) from battlegear2-1.5.8-backhand.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|core (1.5.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|electricity (2.0.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|events (1.0.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|items (1.0.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|locomotive (1.1.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|signals (2.3.0) from Railcraft-9.16.33.jar
		* RailcraftAPI|tracks (2.3.0) from Railcraft-9.16.33.jar
		* RemoteIO|API (2.7.6) from RemoteIO-2.7.6.jar
		* Shield (0.1) from battlegear2-1.5.8-backhand.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-2.1.8-GTNH.jar
		* TC4Tweaks|API (1.5.37) from Thaumcraft4Tweaks-1.5.39.jar
		* TC4Tweaks|API|InfusionRecipeLib (1.5.37) from Thaumcraft4Tweaks-1.5.39.jar
		* Thaumcraft|API (4.2.0.0) from Pam's Harvest the Nether 1.7.10a.jar
		* thaumicenergistics|API (1.1) from thaumicenergistics-1.7.14-GTNH.jar
		* WailaAPI (1.2) from Waila-1.8.14.jar
		* Weapons (0.1) from battlegear2-1.5.8-backhand.jar
	EnderIO: No known problems detected.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Forestry : Info: The following plugins have been disabled in the config: magicalcrops
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, CoFHWrench:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:OFF, GT:ON, Chisel:ON, Jabba:ON, ThaumicTinkerer:ON
	Mixins in Stacktrace: 
		net.minecraft.nbt.NBTTagCompound:
			mixins.hodgepodge.early.json:minecraft.MixinNBTTagCompound_stringPooler from mod hodgepodge_2
			mixins.hodgepodge.early.json:minecraft.MixinNBTTagCompound_speedup from mod hodgepodge_2
		net.minecraft.server.MinecraftServer:
			mixins.bugtorch.early.json:minecraft.fastrandom.MixinMinecraftServer from mod bugtorch
			mixins.visualprospecting.early.json:minecraft.MinecraftServerAccessor from mod visualprospecting
			mixins.hodgepodge.early.json:minecraft.MixinMinecraftServer_RconThreadingFix from mod hodgepodge_2
			mixins.gtnhlib.early.json:MixinMinecraftServer from mod gtnhlib_2
			mixins.serverutilities.early.json:minecraft.vanish.MixinMinecraftServer from mod serverutilities
		cpw.mods.fml.common.eventhandler.EventBus:
			mixins.gtnhlib.early.json:fml.EventBusAccessor from mod gtnhlib_2
			mixins.hodgepodge.early.json:fml.MixinEventBus from mod hodgepodge_2
			mixins.mobsinfo.early.json:minecraft.EventBusAccessor from mod mobsinfo
		net.minecraftforge.common.ForgeChunkManager:
			mixins.archaicfix.early.json:common.core.MixinForgeChunkManager from mod archaicfix
			mixins.hodgepodge.early.json:forge.MixinForgeChunkManager_threadedIO from mod hodgepodge_2
		cpw.mods.fml.common.eventhandler.ASMEventHandler:
			mixins.mobsinfo.early.json:minecraft.ASMEventHandlerAccessor from mod mobsinfo
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by sisyphussy** [comment]
Fixed in 2.8.1

**Comment by Wad67** [comment]
> Fixed in 2.8.1

I have since upgraded to 2.8.1 and I can confirm that the crash still occurs


`[02:53:50] [Server thread/ERROR] [FML]: 49: ASM: gregtech.common.data.GTPowerfailTracker@1fccc21f onWorldLoad(Lnet/minecraftforge/event/world/WorldEvent$Load;)V
[02:53:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Loading NBT data
        at Launch//net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:179) ~[du.class:?]
        at Launch//net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125) ~[du.class:?]
        at Launch//net.minecraft.nbt.CompressedStreamTools.func_152458_a(CompressedStreamTools.java:216) ~[du.class:?]
        at Launch//net.minecraft.nbt.CompressedStreamTools.func_74797_a(CompressedStreamTools.java:200) ~[du.class:?]
        at Launch//net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:421) ~[ForgeChunkManager.class:?]
        at Launch//net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64) ~[ForgeInternalHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_41_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic) ~[?:?]
        at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230) ~[MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258) ~[lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297) ~[?:?]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at Launch//net.minecraft.nbt.NBTTagCompound.func_152447_a(NBTTagCompound.java:383) ~[dh.class:?]
        at Launch//net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:48) ~[dh.class:?]
        at Launch//net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170) ~[du.class:?]
        ... 12 more
[02:53:50] [Server thread/ERROR]: This crash report has been saved to: /home/gtnh/./crash-reports/crash-2025-11-03_02.53.50-server.txt
`


[crash-2025-11-03_02.53.50-server.txt](https://github.com/user-attachments/files/23294695/crash-2025-11-03_02.53.50-server.txt)

**Comment by Wad67** [comment]
Deleting dimensions seems to have lifted the crash, no idea what was doing it although I suspect burnt items in the nether

**Comment by sisyphussy** [comment]
seems like world corruption now
