### ISSUE TITLE
Skeleton Trophy gives epilepsy to anyone holding it.

### ISSUE THREAD

**Issue by firedemontwinkie** [GTNewHorizons/GT-New-Horizons-Modpack#22709]
### Your GTNH Discord Username

firedemontwinkie

### Your Pack Version

GTNH Experimental build 2025-11-15+50

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I expect a normal item that functions as a trophy

### The Reality

everytime it is in hand or hoverd over in a invitory that is opened. the entire screan flashes white and normal very fast. I have tested and it happens on singleplayer as well

https://github.com/user-attachments/assets/8f92f0bc-7729-4224-a200-0affec8660ac

### Your Proposal

dont give people epilepsy when they have the item.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PLASMAchicken** [comment]
Cannot reproduce on daily 260 - uses the non -pre Angelica tho

**Comment by Niasty** [comment]
Happens to me too on 2.8.1, updated with angelica-1.0.0-beta72-pre and gtnhlib-0.8.19 to fix a shader issue
Also, when you put a mob trophy in a chest and look at it with holo glasses on, the entire screen turns white too, though it doesn't flicker.
Same thing when it's in a quest.
This behavior also happens with Witching Gadgets Iconographs, though without the flickering when in inventory

https://github.com/user-attachments/assets/733592bd-3e57-4244-846b-5b24beca5a1d

**Comment by faraday326** [comment]
I am also playing on zeta and I get the exact same effect in multiple places:

1. mousing over the skeleton trophy in NEI
2. opening the completed 'time to kill skeleton' quest (its completed, but haven't gotten the reward yet, if that matters)
3. the worldgen houses that have witchery (skeleton) iconographs. it flipped out for me when i held it in hand.

**Comment by PLASMAchicken** [comment]
> I am also playing on zeta and I get the exact same effect in multiple places:
> 
> 1. mousing over the skeleton trophy in NEI
> 2. opening the completed 'time to kill skeleton' quest (its completed, but haven't gotten the reward yet, if that matters)
> 3. the worldgen houses that have witchery (skeleton) iconographs. it flipped out for me when i held it in hand.

Did you also update GTNHlib / Angelica?'

For 2.8.x GTNHLib 0.7.x is supposed to be used.

**Comment by firedemontwinkie** [comment]
with the new version 52 this also happens with atleast the LV steam turbine trophy. this did not happen in version 50 when I made this post.

**Comment by PLASMAchicken** [comment]
Can you try with latest Angelica 78-pre? 

https://github.com/GTNewHorizons/Angelica/releases/download/1.0.0-beta78-pre/angelica-1.0.0-beta78-pre.jar

**Comment by chochem** [comment]
Should be fixed

**Comment by orbadon** [comment]
This is still happening on Zeta, currently running experimental 71 which has angelica-2.0.0-alpha13

**Comment by orbadon** [comment]
This is no longer happening as of experimental 80 🎉
