### ISSUE TITLE
Nanosuit Boots of the Traveller Infusion Issue

### ISSUE THREAD

**Issue by 1penguinmonk** [GTNewHorizons/GT-New-Horizons-Modpack#2607]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Tried to do the infusion for Nanosuit Boots of the Traveller using a previously charged/damaged Electric Boots of the Traveller.  Expected the infusion to start.
#
#### What happend instead? (Attach screenshots if needed)
The infusion wouldn't start.  The infusion recipe looks for an undamaged Electric Boots of the Traveller which is only possible if you don't charge them after doing their infusion.
![infusion](https://user-images.githubusercontent.com/36487696/36225428-7998ec68-117f-11e8-976b-ea4199c4e69f.PNG)

#
#### What do you suggest instead/what changes do you propose?
Suggest allowing the infusion to use either an undamaged, freshly crafted Electric Boots of the Traveller or boots with any value for its charge/damage.

**Comment by Dream-Master** [comment]
Yes hopfully fixed in 2.0.2.8

**Comment by richardhendricks** [comment]
Still having problems crafting, even with latest Jenkins build, 1088, 2018-02-19

MT info on fully charged boots
![2018-02-19_23 08 08](https://user-images.githubusercontent.com/1214811/36408239-d923d096-15c9-11e8-8929-2985ac579301.png)
Visual info on fully charged boots
![2018-02-19_23 08 16](https://user-images.githubusercontent.com/1214811/36408240-d93243ce-15c9-11e8-97f4-bd092ddb6d91.png)

The electric boots themselves also seem buggy.  Almost impossible to discharge.  Drops when jumping, but if you fall a long distance it recharges.  Also if you take it out of your foot slot, it seems to recharge as well?  

@bartimaeusnek any ideas?

**Comment by richardhendricks** [comment]
BTW the battery and the nanosuit boots I fully discharged as well
![2018-02-19_23 12 31](https://user-images.githubusercontent.com/1214811/36408335-676cbb1a-15ca-11e8-9002-5c112ae6ab13.png)
![2018-02-19_23 12 39](https://user-images.githubusercontent.com/1214811/36408336-677d9d90-15ca-11e8-8ad1-c572159c54f4.png)

**Comment by richardhendricks** [comment]
Wow, nanosuit boots of the traveller are ridiculously fast.  Too fast I'd say. But I am using chisel concrete and thaumcraft paving stones of travel.  I'm making it more for the Vis discount, but sheesh.

**Comment by richardhendricks** [comment]
Also rather annoying it "breaks" the openblocks elevators.

**Comment by bartimaeusnek** [comment]
well I haven't changed them, in 2.0.2.7 at least they worked fine (Nano-Suit Boots and quantum where elevator breaking tho)
I guess the rework breaks the Integer limit when falling so it draws negative amounts of power. I'll fix it when I finished my OC-3D-Printer-Picture-Tool.

**Comment by bartimaeusnek** [comment]
Here's the boots rework: https://github.com/GTNewHorizons/Electro-Magic-Tools/commit/cf167273662dd70e03a0cb3a436745cc2074e903

@richardhendricks

**Comment by bartimaeusnek** [comment]
>  Also if you take it out of your foot slot, it seems to recharge as well?
this might be a visual issure, since the rework made them calculate only server-side without sending information to the client.

**Comment by richardhendricks** [comment]
Is there a build with the fix?  I cheated one in, but I kept the resources for testing.

**Comment by Dream-Master** [comment]
@richardhendricks http://jenkins.usrv.de:8081/job/Electro-Magic-Tools/

**Comment by bartimaeusnek** [comment]
the "fix" is included in my version...

**Comment by Dream-Master** [comment]
@bartimaeusnek isn't the fix in the main repo?

**Comment by PapaTim68** [comment]
I do have the same Problem in 2.0.30 Server

**Comment by Kiwieee** [comment]
This wasn't fully fixed, the nano suit boots have to be charged to exactly 1 durability for the infusion to start
