### ISSUE TITLE
Massive console spam upon opening the Thaumonomicon

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/GT-New-Horizons-Modpack#2742]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Open the Thaumonomicon, expect not to get spammed in the console.
#
#### What happend instead? (Attach screenshots if needed)
I don't know if this is something we can fix, depending on what mod is causing it, but there seems to be some debug message that gets printed constantly while you are looking at the main tabs GUI.  It constantly prints out
`[Client thread/INFO] [STDOUT]: [thaumcraft.client.gui.GuiResearchBrowser:genResearchBackground:531]: 22 1`
#
#### What do you suggest instead/what changes do you propose?
Try to remove whatever debug print message is causing it?  Or can it be suppressed?

**Comment by Dream-Master** [comment]
I am not sure what causing it but i seen it allready too.

**Comment by bartimaeusnek** [comment]
might be related to [this](https://github.com/GTNewHorizons/NewHorizons/issues/2733)

**Comment by Zoko061602** [comment]
Thats my fault, I guess...
Should be fixed when upgrading to 1.1.1a of SuperTiC.

**Comment by Kortako** [comment]
@Zoko061602 I'm already using 1.1.1a from Curseforge to fix the other console spam issue related to tooltips.  You might want to check on that again if that's the case.

**Comment by Kortako** [comment]
@Dream-Master I don't think this issue is fixed yet, why is it marked FixedInDev? Zoko said in #2766 that he didn't fix it. It might not even be his problem?

**Comment by Dream-Master** [comment]
ok it is fixed in 2.0.3.1 dev so far i remeber i dot have any issues with it anymore.

**Comment by Kortako** [comment]
@Dream-Master Just an FYI, I still get this in 2.0.4.0

**Comment by wlhlm** [comment]
This issue still exists in 2.0.8.5 and is caused by [NotEnoughThaumcraftTabs](https://www.curseforge.com/minecraft/mc-mods/notenoughthaumcrafttabs).

Unfortunately, the mod is closed source. In Discord chat @Dream-Master said, that he contacted the author (fewizz) vie email to maybe get this fixed. Otherwise, the mod is MIT licensed according to the CF page, so we could decompile the mod without issue in case the author doesn't respond.

**Comment by wlhlm** [comment]
Here is an excerpt with the offending line from the [decompiled `GuiResearchBrowser` class](https://github.com/GTNewHorizons/NewHorizons/files/4275986/GuiResearchBrowser_nett.java.txt) shipped with NeTT that replaces the corresponding class in Thaumcraft:
```java
// ...
    boolean lefted = false;
    Iterator var34 = researchCategories.iterator();
    max = (ResearchManager.isResearchComplete(this.player, "ELDRITCHMINOR") ? researchCategories.size() - 1 : researchCategories.size() - 2) / 18;
    System.out.println(researchCategories.size() + " " + max);
    
    int oldNumber = 0;
    while (var34.hasNext())
    {
      Object research = var34.next();
      ResearchCategoryList researchCate
// ...
```

**Comment by Prometheus0000** [comment]
So is it fixed then?

**Comment by Dream-Master** [comment]
@wlhlm
