### ISSUE TITLE
Villager trades

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#3051]
As part of fixing the party stuff in BQ, we are going to migrate coins quests to custom villagers over time. It means farming villagers to get the trades you want, or trading with other players on servers etc.

For now, going to test with creating a Banker villager to convert one reward coins type to another, with a small Thaumcraft gold coin fee to make it interesting.

Alk has added an API to GT++ to create custom villagers with specific trades.

VillagerUtils.registerNewVillager(3, "Aboriginal", "Aboriginal", "Aboriginal", "aboriginal", new TradeHandlerAboriginal());

banker
 - trade reward coins (probably 3:2, and will require emeralds)
 - trade TC coins (probably 4:1, no emeralds, only technician)
 - gold/silver for TC coins? (8:1 for silver, 16:1 for gold, can TC coins be melted?)

miner
 - mining equipment, trade for it.  Ticon pick heads?
 - gives ores, like salt in decent quantity, or singles used in vein finding
 - primitive prospector? uses gold nuggets and emeralds?
 - explosives, buy and sell

technician
 - Check Alkalus current implementation

Monsanto Sales Rep
 - Trades ic2 seeds
 - rapeseed
 - coppon
 - stickreeds
 - dyes
 - Some food crops needed for best foods, like tomato

Feed store representative
 - Food items for animals
 - fertilizers
 - simple farming tools, shears, hoe, butcher knife.

Confectionary
 - takes cocoa, sugar, dough
 - sells chocolate and candy/sweets

Artist
 - takes dyes, planks, sticks
 - sells artwork, signs

Forest ranger 
  - Fertilizer
  - Saplings, OW only (vanilla, or pam's too?)

Explorer (Expensive stuff)
 - blaze rods
 - ghast tear
 - some nether ores
 - necro bones
 - Glowstone

**Comment by richardhendricks** [comment]
Requires https://github.com/GTNewHorizons/NewHorizons/issues/2893 to be implemented

**Comment by Prometheus0000** [comment]
Isn't the party stuff fixed now? Is this still going to be a thing?

**Comment by Dream-Master** [comment]
no it isn't fixed. We can set the loot per party or per player.

**Comment by Dream-Master** [comment]
but that mean we  needto edit 2000+ quests.

**Comment by leagris** [comment]
Whatever the # of quests to change, chances are it can be automated by using a JSON processor like `jq`

**Comment by Prometheus0000** [comment]
What exactly is broken then? I thought you could sync your progress with parties as long as you have the same quests completed as them in BQ3, or is syncing not the problem? If it's amount of rewards, since you can just not join a party but still work together, I dunno if there's any way to fix that.
