### ISSUE TITLE
pipes disconect when shutter is of

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5648]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What do you suggest instead/what changes do you propose?
when you trie to control fluid from going in/out of tanks with shutters/pump
the pipe will break the conection with the tank when the shutter is off but not re connect after it is enebled again 
this makes fluid controll very hard

**Comment by Dream-Master** [comment]
@botn365 feel free to do a pr if you like

**Comment by mitchej123** [comment]
Can you provide a screenshot of the setup with details on how to reproduce?  I went to great lengths to ensure the shutters/etc just disabled flow and didn't actually disconnect, exactly because of the issue that you're talking about.

**Comment by repo-alt** [comment]
I think I saw that but thought it is just visual

**Comment by botn365** [comment]
![afbeelding](https://user-images.githubusercontent.com/42187820/75278027-7212b500-5809-11ea-85e5-f04d2f9b51e3.png)

**Comment by Prometheus0000** [comment]
Should be fixed given #5733

**Comment by dgealow** [comment]
This is actually totally still an issue. Ditto for pumps. Ticket should be reopened.

**Comment by dgealow** [comment]
Workaround: Put the controller cover and shutter/pump on the pipe instead of the machine
