### ISSUE TITLE
Bee: one more bee (lime) not recogniced from Gene Bank

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6033]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
once again a bee can't recogniced by GeneBank
Lime bee

![no_Lime_GeneLab](https://user-images.githubusercontent.com/7759876/80921421-96918d00-8d76-11ea-956d-9787a8744c42.JPG)

**Comment by Ngar1** [comment]
one more failure like https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4930

**Comment by Prometheus0000** [comment]
Then why did you make a new issue? Not to mention you ALREADY made an issue on this a week ago. Just make a comment on the original issue.

**Comment by Ngar1** [comment]
The bee version was shifted and in my impression the bee problems are seen as not important. A new issue make them more visual as a comment in a old issue from summer last year >1000 issues before...

**Comment by Prometheus0000** [comment]
It shows up on the github-issues channel regardless. There's no need for new issues. Go look into the code, or find someone who can. There isn't really anything else to do. There are indeed higher priorities right now. If you looked, you would see that 2.0.10 is bees, so it'll probably be handled then.

**Comment by bartimaeusnek** [comment]
this *should be fixed* by now.

**Comment by Ngar1** [comment]
testet with GTNH-1.7.10-2.0.9.0-pre7-dev.zip same world, SP  -> not solved

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea?

**Comment by Ngar1** [comment]
Not solved in 2.1.1.0
