### ISSUE TITLE
[List] Empty Cutting Machine Recipes

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6102]
#### Which modpack version are you using?
2.0.8.3
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
### 0.  GregTech
- Empty>Empty ?
![изображение](https://user-images.githubusercontent.com/47714084/81796165-b9aa0280-9515-11ea-9e15-db5aa4f4eef9.png)
-  #6071 
-  Block of Blaze [2063:5]
- Blazing Rod
-  Stone/Cobblestone Rod [6288]/[7089:23299]
-  Basalt [2051:8]
-  Basalt Cobblestone [2051:9]
-  Mossy Basalt Cobblestone [2051:10]
-  Basalt Bricks [2051:11]
-  Cracked Basalt Bricks [2051:12]
-  Mossy Basalt Bricks [2051:13]
-  Chisiled Basalt [2051:14]
-  Smooth Basalt [2051:15]
- Block of Rock Salt
### 1. BartWorks
- FIXED (Bart)
### 2. GT++
-  Blizz Rod [8858:1]
-  item.itemRodCalifornium.name [10369]
-  item.itemRodThorium232.name [10397]
### 3. Ztones
-  Agon [1700:0-15]
-  Bitt [1701:0-15]
-  Iszm [1704:0-15]
-  Jelt [1705:0-15]
-  Korp [1706:0-15]
### 4. Chisel
-  Andesite [1373]
-  End Stone [1393]
### 5. Extra Utilites
-  Unstable Ingot Block [1099:55]
### 6. Pam's HarvestCraft
-  Compressed Salt Block [1861]
### 7. Biomes O' Plenty
-  Block of Malachite [812:11]
#
**Every recipe have 3 variant(water,dist. water and lubricant)**

**Comment by leagris** [comment]
Maybe the recipe adder for the Cutting Machine could check the Output items actually exists before adding recipe to the map.

**Comment by bartimaeusnek** [comment]
Mine are fixed now ^^

**Comment by Prometheus0000** [comment]
See #5819 as well

**Comment by dimondmine2** [comment]
Not sure why the issue was marked closed. The issue is still present

![image](https://user-images.githubusercontent.com/75643342/108139543-4332c600-708e-11eb-8cad-89e5449d7486.png)

**Comment by bombcar** [comment]
There are 103 pages of these.

Is it possible in code to find all "no output cutting machine recipes" using what @D-Cysteine does in https://github.com/D-Cysteine/nei-custom-diagram/wiki/Diagrams#gregtech-recipe-debugger and just remove them? Or would it be easier to just make the machine refuse to run them?
