### ISSUE TITLE
CAL energy consomption/overclocking issue

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7016]
#### Which modpack version are you using?
2.0.9.3.a.dev

I updated my world from 2.0.9.0.QF4 to 2.0.9.3.a.dev and I noticed that now my UEV circuit assembly lines don't overclock properly. For exemple when doing this recipe at UEV power it takes 14 seconds : 
![image](https://user-images.githubusercontent.com/57050655/100530608-6323bd80-31f4-11eb-87ad-26e700859171.png)

And the scanner says : 
![image](https://user-images.githubusercontent.com/57050655/100530616-6d45bc00-31f4-11eb-8a69-1dface33d942.png)

**Comment by Prometheus0000** [comment]
Please check more than 1 machine type, so we can tell if it's just the CAL or all UEV stuff or what. Also, I think bot was doing something to fix UEV PAs OC or something? It might be related

**Comment by botn365** [comment]
i have that patched on my gt5u and dont have this problem with uiv energy hatches

**Comment by Alexdoru** [comment]
I haven't noticed any problem with the other UEV multis I have.

**Comment by Alexdoru** [comment]
So after restarting my world I noticed that for the first craft the CAL is working correctly with the good recipe duration and energy concumption. However all the next crafts it's completely fucked up.

For instance for this craft it should be doing 7.5sec and 2.4m eu/t but it's doing this 

![image](https://user-images.githubusercontent.com/57050655/100544672-a2372a80-3257-11eb-8f16-2e8659581e0e.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ? or fixed in past 2.0.9.0 version ?

**Comment by bartimaeusnek** [comment]
I cant replicate this glitch indev. No idea @Dream-Master

**Comment by Alexdoru** [comment]
I crafted a new CAL and new imprint, and the bug is still here, with UEV energy hatch the first craft is working ok with the right overclock and then all the crafts after that are with wrong eu/t and durations

**Comment by Alexdoru** [comment]
I updated to 2.0.9.4.a.dev and the issue is stil here : 
![image](https://user-images.githubusercontent.com/57050655/101283641-0324ac80-37dc-11eb-8e21-1730d838e50a.png)

How did you build the CAL when you tested to not have the issue ? @bartimaeusnek

**Comment by Alexdoru** [comment]
I installed GTNH 2.1.0.0.pre.dev, installed no extra mods, created a new world and the bug is still here.
Is my computer or my java broken or is there a bug with your mod ? Can you have a look at it

@bartimaeusnek 

![image](https://user-images.githubusercontent.com/57050655/102664565-5eaf4c80-4183-11eb-932c-e3a7d4e046e5.png)

**Comment by Dream-Master** [comment]
> I cant replicate this glitch indev. No idea @Dream-Master

How i can know what went wrong here? I dont know what are you put inside your dev version. Are yu using newest gt version for testing

**Comment by Glease** [comment]
https://github.com/GTNewHorizons/bartworks/blob/6c26f91bd618f7845b56e88360ec3c86ffc9eecf/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_CircuitAssemblyLine.java#L124

https://github.com/GTNewHorizons/bartworks/blob/6c26f91bd618f7845b56e88360ec3c86ffc9eecf/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_CircuitAssemblyLine.java#L156

First craft's overclocking and remaining craft's overclocking are not calculated using the same method. i don't know if this is intentional nor do I understand the implication of this difference but it doesn't seem right

**Comment by Alexdoru** [comment]
So I installed your fixed version and now the power consomption is good however it is doing a normal overclock and not a perfect overclock 

![image](https://user-images.githubusercontent.com/57050655/102693641-5c4d0100-421c-11eb-9ad7-a04521d6e329.png)
