### ISSUE TITLE
AE2 GT EU P2P won't transmit power on world load in a specific situation

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#8442]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

A video showing the issue: 

[![Video showing the issue](https://img.youtube.com/vi/x8MdI9ZneVE/0.jpg)](https://www.youtube.com/watch?v=x8MdI9ZneVE "GT EU P2P Acting Strangely")

The Setup: build two separate areas, outside of render range of each other; a Power Area and a Work Area. 

The Power Area contains a quantum bridge, a world anchor (I used an admin anchor), and a GT EU P2P input connected to some form of generator. I've tried battery buffers and Naquadah Reactors. I've also tried connecting cables between the P2P input and the generators, and putting the generator directly on the P2P input. For the purposes of this example, I used LuV generators and energy hatches. I used neutronium energy cells to power both sides of the quantum bridge.

The Work Area contains a quantum bridge paired to the Power Area's QB, a world anchor, and a Vacuum Freezer. The Vacuum Freezer is powered by a GT EU P2P output, paired to the input in the Power Area. 

Configuring the Vacuum Freezer: Attach a machine controller to the Vacuum Freezer, set it to active low and turn safe mode on. Attach a level emitter to the network, and leave its configuration blank. (This drives a signal high when the network is fully functional.) Place a NOT gate on the level emitter, and run a lead from the NOT gate's output to the machine controller. 

I expect the p2p power link to continue transmitting to the Work Area on game load, given that both areas are chunkloaded.

### The Reality

Reproducing the bug: First, give the Vacuum Freezer something to do. I created a simple compressed air to liquid air loop, and voided the liquid air. While at the Work Area, quit the game to the title menu. Load the game back up. When you load, the level emitter will be off briefly while the ME network rebuilds itself. Once it turns back on and the game catches back up, the Vacuum Freezer will go into a low power loop, voiding inputs. Inspecting the WAILA tooltip of the P2P GT EU output will show that the P2P link is properly paired. Using a tricorder on the energy hatch and the controller will show zero power inside the multiblock. 

Teleporting to the Power Area, allowing it to load, and then teleporting back to the Work Area will properly reform the link. The Vacuum Freezer will begin working properly again. You don't have to do anything in the Power Area, just be physically present long enough for it to load.

Additionally, the Safe Mode setting on a machine controller appears to not function at all for the Vacuum Freezer. 

### Your Proposal

I would expect the link to form properly, considering that both areas are chunkloaded, even if the Power Area has been unvisited by a player. I would also expect the Safe Mode feature of a machine controller to at least shut down the vacuum freezer in the event of a power underrun.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sintken** [comment]
i have experienced a similar thing - gt eu p2ps receiving power from a turbine array and sending it via p2p to a LSC. Every chunk in between the turbines and the lsc has an anchor such that they load each other on login, but for the power to transmit properly i have to physically go to and load the turbines and lsc separately.

**Comment by querns** [comment]
Some additional context: I attempted to sever the connection between the quantum bridge and EU p2p connector remotely using a wireless redstone receiver and a wireless redstone remote outputting to an inverted toggle bus. I also attempted to cause block updates adjacent to the p2p connector using a block breaker/placer combo to continually drop and break a cobblestone block. Neither worked.

**Comment by repo-alt** [comment]
I beleive it is already fixed in dev, try with the latest GT5 from Jenkins

**Comment by querns** [comment]
Confirmed -- the August 16th build of AE2 indeed fixes this issue. Thanks!

One minor note: the new build still shows up as `beta-27` in MultiMC. I don't know if this is something that has to be manually changed or if it's something that a build process handles, so ignore if not relevant.

![image](https://user-images.githubusercontent.com/33518699/130788845-5ddc3195-2726-4576-9645-9eff24d58fdc.png)

Otherwise, this ticket can be closed. Thanks!
