### ISSUE TITLE
Advanced Coke Oven Making Coal Coke from Charcoal

### ISSUE THREAD

**Issue by DragonStorm25** [GTNewHorizons/GT-New-Horizons-Modpack#9093]
### Your GTNH Discord Username

Ant#3686

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Tried to put charcoal into advanced coke oven. Expected no output, which occurs in previous versions.

### The Reality

Advanced coke oven outputted one coal coke after 20 ticks, which matches the coal -> coal coke recipe in the advanced coke oven.

### Your Proposal

Fix it, from every other recipe coal coke should not be easily renewable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Wired maybe appears since we change a lot in rc

**Comment by Houndie** [comment]
Just providing a data point, since this was mentioned in the PR above, this still occurs in 2.1.2.3qf

**Comment by Dream-Master** [comment]
Impossible but i check ingame

**Comment by Dream-Master** [comment]
nope cant reproduce

**Comment by Dream-Master** [comment]
@Houndie ahow me the recipe ingame

**Comment by z3r0b0t** [comment]
Hi @Dream-Master, the recipe is actually not showing in NEI, but it's definitely processing. I'm on delta and when my wood runs out for my benzene setup, sometimes some of the charcoal actually goes back into the advanced coke ovens and produces coal coke... I've had my setup for a while, I came back on the pack a few weeks ago and didn't really bother with the issue as I fixed the supply of wood, but this is still happening from time to time.
![image](https://user-images.githubusercontent.com/36605286/161411634-8e9b86d9-36a8-4fbf-8a54-7a8689936b80.png)

IIRC We are on 2.1.2.0 now on delta, at least that's what my client is showing.

**Comment by z3r0b0t** [comment]
I've also confirmed this still happens on the latest build in curse : 
![image](https://user-images.githubusercontent.com/36605286/161412198-9cc3c626-a115-4caa-8049-00ce4ca85046.png)
![image](https://user-images.githubusercontent.com/36605286/161412211-e824a65d-3671-4225-bdd3-695ffcf8d53c.png)

**Comment by Dream-Master** [comment]
Will test with my 2.1.2.4 dev version later

**Comment by PeachCheetah** [comment]
I am also seeing this issue in my world. I don't see the recipe in NEI but it still allows the recipe.

**Comment by Dream-Master** [comment]
fixed pre 2.1.2.3qf

**Comment by NoX-programer** [comment]
2.1.2.3qf: bug still exists.

**Comment by ChromicRedBrick** [comment]
This bug still exists in 2.2.0.0-RC-1.

Advanced coke oven can make coal coke from coal, which is not intended, because coke oven cannot do so, neither do pyrolyse oven or industrial coke oven.

NEI doesn't show that adv coke oven can turn charcoal to coal coke, and this recipe should not exist anyway.

Also I think this is NOT an NEI bug, it is a Railcraft bug: adv coke oven cannot distinguish charcoal from coal, -- they share the same item ID, but are different in metadata.

Video: https://youtu.be/w6a11qPIRCM

**Comment by boubou19** [comment]
> This bug still exists in 2.2.0.0-RC-1.

It's not even released yet

**Comment by ChromicRedBrick** [comment]
But the version number in mainmenu is already 2.2.0.0-RC-1 :)

**Comment by boubou19** [comment]
Still, you should name precisely the version you are using, as this bug isn't guaranteed to be looked at anytime soon, so an accurate history is required.

**Comment by ChromicRedBrick** [comment]
> Still, you should name precisely the version you are using, as this bug isn't guaranteed to be looked at anytime soon, so an accurate history is required.

All right, edited.

**Comment by thibaut-fagart** [comment]
i can see this too in 2.2.0.0 : i have an advanced coke oven fed by 2 sets of items pipes: 1 providing charcoal ( also collecting output) and 1 providing spruce wood. 
After a while the oven started making coal coke, as both fuel and input slots filled with charcoal (guess the wood was not being delivered fast enough)

**Comment by dvdmandt** [comment]
Can confirm it's in 2.2.3 as well. It doesn't show up in NEI, but placing charcoal in the top slot does indeed still produce coal coke.

**Comment by Cleptomania** [comment]
I've made a PR to fix this in Railcraft: https://github.com/GTNewHorizons/Railcraft/pull/32

Tested the fix with 2.2.3
