### ISSUE TITLE
dream craft fails on multiple recipes

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9567]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.2

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

we should load peacefully and quietly

### The Reality

When loading, dream craft tracebacks on a bunch of recipes

```
[08:25:05] [Client thread/ERROR] [DREAMCRAFT]: a recipe went wrong:
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:33)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.dreammaster.scripts.IScriptLoader.addShapedRecipe(IScriptLoader.java:97)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.dreammaster.scripts.ScriptBiblioWoodsNatura.loadRecipes(ScriptBiblioWoodsNatura.java:253)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.dreammaster.gthandler.GT_CraftingRecipeLoader.run(GT_CraftingRecipeLoader.java:333)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.dreammaster.gthandler.GT_CustomLoader.run(GT_CustomLoader.java:193)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.dreammaster.main.MainRegistry.PostLoad(MainRegistry.java:424)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[08:25:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7926378/fml-client-latest.log)

### Your Proposal

fix it

possibly script move change? something doesn't exist at the time it needs it?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
i thought i fixed all of those already. Will look into it

**Comment by bombcar** [comment]
This is in the zip, maybe the latest on Jenkins fixes; I can check

**Comment by bombcar** [comment]
Still happens on latest build even with updated dependencies.

**Comment by boubou19** [comment]
then i'll commit a fix for that this evening

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/269
